.github/workflows/ci.yml
Cargo.toml
src/interpreter/gas.rs
src/profiler.rs
tests/code_coverage.rs

Adds per-instruction code coverge profiling, i.e. keeps track of all executed addresses

Code coverge profiling

---

src/consts.rs

Not used, `CONTRACT_MAX_SIZE` was used instead.

Remove unused constant for contract size.

---

src/interpreter/metadata.rs
tests/metadata.rs

GM was returning the opposite of what it should've when checking if the caller was external. Instead of setting rA = true when the caller was external, we set rA = true when the caller was internal.
fixes: https://github.com/FuelLabs/fuel-vm/issues/83

Fix GM opcode for returning the opposite result

---

Cargo.toml
src/error.rs
src/interpreter/executors/main.rs
src/interpreter/initialization.rs
src/interpreter/internal.rs
src/interpreter/post_execution.rs
src/lib.rs
src/util.rs
tests/outputs.rs
tests/validation.rs

Variable outputs need to be updated directly on the serialized transaction representation in VM memory for IVG purposes. However, there was a bug when writing the variable output changes such that the wrong offset was used, potentially overwriting freebalances.
This PR also makes change outputs consistent between the serialized tx and ref tx. Since if the serialized tx matches the VM referenced tx after post-execution, the tx won't need to be recloned and serialized later in the client for merkleizing.

Variable output bugfix

---

Cargo.toml
src/interpreter/executors/instruction.rs
src/interpreter/gas.rs
src/interpreter/gas/consts.rs
src/util.rs
tests/alu.rs
tests/backtrace.rs
tests/blockchain.rs
tests/contract.rs
tests/crypto.rs
tests/flow.rs
tests/metadata.rs
tests/outputs.rs
tests/predicate.rs
tests/validation.rs

Implement MOVI opcode and replace non-idiomatic usages of `ADDI r 0 imm`.
This unblocks support for transactions with 255 inputs, since their script data offsets are now too large to fit in an ADDI imm12.
blocked by: https://github.com/FuelLabs/fuel-asm/pull/53

Implement MOVI opcode

---

src/interpreter/executors/main.rs
src/interpreter/flow.rs

Removed a todo that was already implemented in another method (post_execution::finalize_outputs)

Cleanup todo for reverts

---

.github/workflows/ci.yml
Cargo.toml
src/interpreter/constructors.rs
src/profiler.rs
tests/serde_profile.rs

Currently the data produced by the profiler cannot be serialized to JSON using Serde, as the data model requires object keys to be strings. Rust doesn't detect this at compile time, and the data was already usable in most binary formats like bincode. This PR makes it possible to serialize the data as JSON, but unfortunately Serde doesn't allow different formats for binary files, so this also increases size of bincode-encoded profile files.
This PR also adds `Send + Sync` trait bounds to the profile receiver, so that it can be used in multithreaded contexts, like in `async` functions.

Profiler fixes

---

src/interpreter/alu.rs
src/interpreter/executors/instruction.rs
tests/alu.rs

fixes: https://github.com/FuelLabs/fuel-vm/issues/121
Uses u128 math for all the instructions that need to treat the overflow register as the high bits of a u128. This will unblock the stdlib impl of u128 types.
This includes:
- add
- addi
- mul
- muli
- sll
- slli
- srl
- srli
- sub
- subi
The wording of the specs was somewhat confusing for srl & srli, since a logical shift right can't underflow. However, the specs describe the same `$of` behavior as other opcodes which do have under/overflow.

Capture overflow value instead of overflow state into `$of`

---

src/interpreter/executors/instruction.rs
tests/flow.rs

fixes: #126 
Expected Behavior:
The expected behavior for a revert is to immediately cease execution of opcodes, and only include one revert receipt.
Actual Behavior:
When a contract call reverted, the VM appended two revert receipts.
Summary:
The root cause is that while `run_call` correctly returned a revert state, this result was then discarded by the parent stack and not propagated. Since revert doesn't increase $pc, the same opcodes would run again on the parent stack (callee) causing the receipt to be appended twice.
The fix simply checks the result of `call` and returns with the Revert state if needed.

Duplicate revert receipt fix

---

src/interpreter.rs
src/interpreter/constructors.rs
src/interpreter/executors/main.rs
src/interpreter/initialization.rs
src/interpreter/internal.rs
src/interpreter/memory.rs
src/memory_client.rs
src/transactor.rs
src/util.rs
tests/alu.rs
tests/crypto.rs
tests/flow.rs
tests/metadata.rs
tests/predicate.rs

continuation of https://github.com/FuelLabs/fuel-tx/issues/114

Add consensus params to the vm for tx validation

---

src/interpreter/executors/instruction.rs

This minor issue is preventing predicates from being integrated into fuel-core. The instruction executors need to be public in order to use the public apis for executing individual instructions when debugging.

make instruction executors accessible

---

src/interpreter/contract.rs
src/interpreter/executors/main.rs
src/interpreter/flow.rs
src/interpreter/internal.rs
src/interpreter/log.rs

The VM memory section for the receipts root was updated only after the
script execution.
It is desirable to have it updated on the fly so the scripts can consume
the generated receipts root.
Closes #125

Update VM memory for receipts root after append

---

src/lib.rs
src/util.rs

- Fix hygiene of script_with_data_offset so that no other imports are externally required.
- Fullly re-export all fuel-* prelude deps to simplify downstream dep management.

Improve hygiene of `script_with_data_offset!`

---

src/interpreter/executors/instruction.rs

This is a non-breaking change, but prepares for the next release of fuel-asm which doesn't have SLDC anymore.
Closes #143

Remove unimplemented SLDC opcode

---

Cargo.toml
src/interpreter/initialization.rs
src/memory_client.rs
src/storage/memory.rs
src/util.rs
tests/validation.rs

The VM was passing the default block height to tx validation before it was set. 
This PR updates the init logic to use the height passed in to the init function instead of relying on when the block height is set on the interpreter.
fixes: https://github.com/FuelLabs/fuel-core/issues/432

fix block height when performing tx validation

---

src/interpreter/executors/main.rs

disable duplicative predicate verification checks when submitting create txs. Predicate verification should be executed by the client / txpool, not when a tx is run by the vm.
partially adresses: https://github.com/FuelLabs/fuel-core/issues/449

Disable faulty predicate checks during create tx execution

---

src/interpreter/flow.rs
tests/flow.rs

When a script calls a contract, a Call receipt is appended. If I'm reading [the spec](https://github.com/FuelLabs/fuel-specs/blob/master/specs/vm/instruction_set.md#call-call-contract) correctly, in such a case, the call receipt's `to` field should be the called contract's ID, and the `from` field should be `0x0000...`, indicating that it was called from the script.
We were putting the contract's ID on both `to` and `from` fields and this PR aims to fix that.
The issue was:
- To initiate the call, we modify `REG_FP`.
- When creating the receipt, we check `self.registers[REG_FP] == 0` to see if the call is external.
- This gives an unexpected result because `REG_FP` was modified.
The fix is basically reading the value for the `from` field before `REG_FP` gets modified.

Fix `Recipt::Call`s having the wrong `id`

---

src/context.rs
src/interpreter.rs
src/interpreter/blockchain.rs
src/interpreter/constructors.rs
src/interpreter/contract.rs
src/interpreter/executors/instruction.rs
src/interpreter/executors/main.rs
src/interpreter/executors/predicate.rs
src/interpreter/flow.rs
src/interpreter/initialization.rs
src/interpreter/internal.rs
src/interpreter/memory.rs
src/interpreter/metadata.rs
src/lib.rs
src/predicate.rs
tests/predicate.rs

The context of the execution should contain more info such as the index
of the current predicate so we decouple that from the vm initialization.
Also, its worthy to create a type that will encapsulate the behavior of
the runtime predicates since it needs to store not only the program to
be executed - so it can't be represented just as a memory slice - but
the original input index that created the predicate.
The input index is not required for the predicate execution since the
program memory offset is a constant function of the consensus
parameters, but it might be consumed by the user - as in the specs.

Implement GM::GetVerifyingPredicate metadata instr

---

src/interpreter/executors/main.rs

As pointed by @mediremi , we might overflow on the post-execution gas
deduction.
That operation must be safe, so we have to use `checked_sub`

Fix gas subtraction overflow

---

.github/workflows/ci.yml
Cargo.toml
src/error.rs
src/interpreter/executors/main.rs
src/interpreter/flow.rs
src/interpreter/gas.rs
src/lib.rs
tests/bug-id.rs

Some states of the VM are ultimately invalid and contradict the
specifications constraints. These maps to implementation errors that
must be fixed.
In order to make it easier for the user to spot these errors, we must
have a reliable reporting system.
As a first step, its important to map the origin of the error. This
commit introduces `Bug`, that will provide meaningful descriptions to
circumstances that violates the specifications constraints, and `BugId`,
that is guaranteed by tests to map to a specic - and unique - location
of the code.

Add traceable bug id to unexpected behavior

---

Cargo.toml
src/interpreter/executors/instruction.rs
src/interpreter/executors/instruction/tests.rs
src/interpreter/executors/instruction/tests/reserved_registers.rs

add some light quickcheck fuzzing to ensure reserved registers can't be written to. It uses a match over opcode variants to explicitly specify which opcodes are expected to write to rA. This will help with future proofing against future opcodes, as this match (`writes_to_ra`) will have to be updated.
may replace: https://github.com/FuelLabs/fuel-vm/pull/186

Quickcheck reserved register access

---

Cargo.toml
src/interpreter/metadata.rs
src/predicate.rs
tests/alu.rs
tests/blockchain.rs
tests/metadata.rs

closes #204 
In order to remove it - I have updated fuel-tx and fuel-asm to latest versions where the `owner` field is already removed.
Then I have updated the code and the tests.

Remove owner field from MessageInputs 

---

src/interpreter/flow.rs

This commit introduces a function to allow users to simulate a call operation without executing the loaded code/context.
This operation is desirable for bug reproduction or isolated analysis of instruction executions. Prior to this commit, its impossible to execute contract instructions in isolation.
This function is expected by the benchmark so an analysis can be done of the contract operations without the need to correct the results with the call overhead.

Add `Interpreter::prepare_call`

---

Cargo.toml
src/arith.rs
src/error.rs
src/lib.rs

This module aims to centralize all arithmetic operations so they can be easily updated whenever required.
It is desirable to run all protocol checked operations as unchecked code, but then it will be feasible only after we have comprehensive test coverage.
Closes #214
Relates to #170

Add `arith` module

---

src/interpreter/executors/main.rs
src/storage/interpreter.rs

Consumers of the VM might want to replicate the contract deployment also to emulate the behavior of storages.
Currently, the only way to do that is via a `Create` transaction, but then we might want to facilitate this operation without creating the whole transaction requirements in order to allow complex operations such as benchmarking.
This commit introduces the ability to add a contract into an interpreter storage using the same strategy that transaction execution would use. It is added as part of the storage because the responsibility for the implementation is a concrete aspect of the database backend.

Add `InterpreterStorage::deploy_contract`

---

Cargo.toml
src/call.rs
src/crypto.rs
src/error.rs
src/interpreter/crypto.rs
src/interpreter/executors/main.rs
tests/crypto.rs

This commit applies safe arithmetic to call and crypto interpreter
modules.
The deprecated implementation of secp256k1 was not using safe
arithmetic. Instead of updating it, the module was deprecated in favor
of fuel-crypto.

Apply safe arith to call and crypto

---

src/interpreter/flow.rs
tests/flow.rs

Fix bug in `RETD` which throws `MemoryOverflow` for buffers at the very top of RAM.

---

src/interpreter/executors/main.rs
src/memory_client.rs
src/state.rs
src/transactor.rs
src/util.rs
tests/blockchain.rs
tests/gas_factor.rs

Removes a transmute that is never actually used.
Also this transmute crates a self reference that is UB when the struct is moved.

Remove transmute

---

src/interpreter/contract.rs
tests/outputs.rs

Closes #237.
- Adds `TransferOut` receipt to receipt output for `transfer_output()`
All tests pass.
(First PR in fuel-vm; let me know if I should do something else)

Append TransferOut receipt for transfer_output

---

Cargo.toml

* Test safe arithmetic checks in blockchain.rs by @mitch-fuel in https://github.com/FuelLabs/fuel-vm/pull/202
* Apply safe arith to call and crypto by @vlopes11 in https://github.com/FuelLabs/fuel-vm/pull/203
* Tests for Safe Arithmetic Checks in crypto.rs by @mitch-fuel in https://github.com/FuelLabs/fuel-vm/pull/207
* Use common utility functions over duplicate implementation in blockchain.rs by @mitch-fuel in https://github.com/FuelLabs/fuel-vm/pull/224
* Fix bug in `RETD` which throws `MemoryOverflow` for buffers at the very top of RAM. by @otrho in https://github.com/FuelLabs/fuel-vm/pull/229
* Remove transmute by @freesig in https://github.com/FuelLabs/fuel-vm/pull/199
* Add warning comment to gas_cost_const by @freesig in https://github.com/FuelLabs/fuel-vm/pull/198
* Add gas …

Bump version to `0.19.0` for release

---

src/interpreter/executors/instruction/tests/reserved_registers.rs

After the recent addition of a gas price schedule, one of our proptests would randomly run into out of gas errors.
fixes: #236

fix test flakiness

---

Cargo.toml
src/interpreter/executors/instruction.rs
src/interpreter/executors/instruction/tests.rs
src/interpreter/executors/instruction/tests/math_operations.rs

Closes #150.
See https://github.com/FuelLabs/fuel-vm/issues/150#issuecomment-1288797787 for detailed explanation and benchmark.
This is a minor breaking change: it fixes a bug, but it's unlikely that anything is depending on the broken behavior.
This contains a performance regression, but correctness is more important here. ~~In any case, this has to be benchmarked and gas cost adjusted.~~ Initial benchmarking shows no significant impact. Either the benchmark needs to be changed to add the edge cases, or the pricing is good enough already.

Avoid rounding issues in MLOG instruction

---

src/storage/interpreter.rs
src/storage/memory.rs
src/storage/predicate.rs

add breaking interface changes now so we can patch in range functionality later without breaking version changes. 
This is in support of https://github.com/FuelLabs/fuel-specs/pull/414

State Range Ops on InterpreterStorage trait

---

src/consts.rs
tests/blockchain.rs

@freesig noticed the vm max memory was configured incorrectly, it should be 64 MiB, whereas it was previously set to 64 M words.
fixes: https://github.com/FuelLabs/fuel-core/issues/732

fix max mem to correctly be 64MiB

---

src/interpreter.rs
src/interpreter/executors/main.rs
src/util.rs
tests/outputs.rs

Update outputs of `Create` transaction after execution and added unit test to cover this case.

Bugfix: Update outputs of `Create` transaction after execution

---

src/interpreter.rs
src/interpreter/blockchain.rs
src/interpreter/constructors.rs
src/interpreter/contract.rs
src/interpreter/flow.rs
src/util.rs
tests/blockchain.rs

Fix for https://github.com/FuelLabs/fuel-vm/pull/255 and https://github.com/FuelLabs/fuel-vm/pull/233

Added a temporary field used by `Receipt::Panic` to fill `contract_id` if any

---

Cargo.toml
src/interpreter/executors/instruction.rs
src/interpreter/memory.rs
tests/memory.rs

fixes https://github.com/FuelLabs/sway/issues/3436
Load byte was using the `RegisterId` instead of the actual registers value as the memory offset.

Fix bug in load byte

---

.github/workflows/ci.yml
Cargo.toml
fuel-crypto/Cargo.toml
fuel-crypto/LICENSE
fuel-crypto/README.md
fuel-crypto/benches/signature.rs
fuel-crypto/src/error.rs
fuel-crypto/src/hasher.rs
fuel-crypto/src/keystore.rs
fuel-crypto/src/lib.rs
fuel-crypto/src/message.rs
fuel-crypto/src/mnemonic.rs
fuel-crypto/src/public.rs
fuel-crypto/src/secret.rs
fuel-crypto/src/signature.rs
fuel-crypto/src/signer.rs
fuel-crypto/tests/hasher.rs
fuel-crypto/tests/mnemonic.rs
fuel-crypto/tests/serde.rs
fuel-crypto/tests/signature.rs
fuel-crypto/tests/signer.rs
fuel-tx/Cargo.toml
fuel-tx/test-helpers/Cargo.toml
fuel-vm/Cargo.toml

This PR is based on @ControlCplusControlV's WIP merge in #274.
This PR merges the `fuel-crypto` repository into this repo (in a history-preserving manner) to avoid introducing a dependency cycle between the `fuel-vm` and `fuel-crypto` repositories as highlighted [here](https://github.com/FuelLabs/fuel-vm/pull/274#issuecomment-1336388924).
**NOTE:** If/when we merge this into @ControlCplusControlV's branch, we should *not* use the "Squash" option and instead should add a new merge commit. Otherwise, I think we risk squashing the preserved history commits included within this PR into a single commit, which is probably not what we want.
cc @adlerjohn @sezna I think one of you might need to re-enable the option to merge without squashing temporarily until both this PR and #274 have landed?

Include the `fuel-crypto` repo in the great "Summon the MonoRepo" merge

---

src/interpreter/log.rs
tests/flow.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/282
This is quite similar to https://github.com/FuelLabs/fuel-vm/pull/229

Fix bug in `LOGD` which throws `MemoryOverflow` for buffers at the very top of RAM

---

fuel-tx/src/receipt.rs
fuel-vm/tests/flow.rs

We have optional methods for fetching contract id's from receipts, however the VM returns all zeros instead of None. This caused unexpected failures since downstream we expect these methods to only return Some if there is a real contract id.
If contract id is zeroed, convert to an Option::None when fetching receipt fields.

Return `None` for zeroed `ContractId` in `Receipt`

---

fuel-merkle/src/binary/in_memory.rs
fuel-merkle/src/sparse/in_memory.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sparse/node.rs

Similar to https://github.com/FuelLabs/fuel-merkle/pull/141, this PR separates the SMT implementation blocks across mutable and immutable storage. In some cases, we need to be able to call methods, such as `root` when the tree only has immutable storage access. When a method does not need mutable storage access, these methods can now be called.

feat: Separate SMT impls for mutable and immutable storage

---

fuel-merkle/src/binary/merkle_tree.rs
fuel-merkle/src/sparse/hash.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sum/merkle_tree.rs
fuel-vm/src/storage.rs

After https://github.com/FuelLabs/fuel-core/pull/917 I realized that it would be nice to have some additional methods.
- Added static `empty_root` method to all Merkle trees.
- Added new constructors for double storage key.

Some improvements of API after integration of previous release into `fuel-core`

---

fuel-merkle/src/binary/in_memory.rs
fuel-merkle/src/binary/merkle_tree.rs

Changes:
- Remove mut requirement from in memory BMT `root`
- Remove `MerkleTreeError` wrapper around BMT `push` StorageError in return type

chore: BMT clean up

---

.github/workflows/ci.yml
fuel-asm/src/panic_reason.rs
fuel-asm/tests/encoding.rs
fuel-crypto/src/error.rs
fuel-crypto/tests/signature.rs
fuel-merkle/src/common/prefix.rs
fuel-tx/src/contract.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/input/repr.rs
fuel-tx/src/transaction/types/output/repr.rs
fuel-tx/src/transaction/types/utxo_id.rs
fuel-tx/src/transaction/validity/error.rs
fuel-tx/src/tx_pointer.rs
fuel-types/tests/types.rs
fuel-vm/src/checked_transaction.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/instruction/tests/math_operations.rs
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/post_execution.rs
fuel-vm/src/profiler.rs
fuel-vm/tests/outputs.rs
fuel-vm/tests/profile_gas.rs

Replaces our custom (although stdlib-inspired) solution with a call to the now-stable function in the stdlib.
This PR also upgrades CI Rust version to 1.67 which stabilized this function. This in turn requires some minor changes to appease clippy.

Use the recently stabilized checked_ilog

---

fuel-tx/src/tx_pointer.rs

Tiny PR that provides a display implementation using the `LowerHex` representation, following suit with the `fuel-types` `Display` implementations. Came across the desire for this while working on the new `forc-tx` command.

Implement `fmt::Display` for `TxPointer`

---

fuel-merkle/src/common/path_iterator.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sum/merkle_tree.rs

- https://github.com/FuelLabs/fuel-core/issues/527
Removes `Clone` constraint from `PathIterator` by using `take` instead of `clone`. Requiring `Clone` is too cumbersome because it requires that the `ParentNode::Error` (e.g., `StorageError` in the case of `fuel-core`) also implement `Clone`, which cannot be guaranteed.

Remove `Clone` constraint from `PathIterator`

---

Cargo.toml

* Use the recently stabilized checked_ilog by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/332
* Added additional methods for storage for the cases when the developer need to work with `StorageAsRef` and `StorageAsMut` by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/331
* Implement `fmt::Display` for `TxPointer` by @mitchmindtree in https://github.com/FuelLabs/fuel-vm/pull/334
* Updated `publish-crates` by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/333
* Remove `Clone` constraint from `PathIterator` by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/336
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.25.2...v0.25.3

bump 0.25.3

---

fuel-asm/Cargo.toml
fuel-asm/src/lib.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/tests/spec.rs

Implementation of https://github.com/FuelLabs/fuel-specs/pull/457
This is technically a breaking change, but it's unlikely that anyone was relying on this behavior.

Do not allow setting reserved flags

---

Cargo.toml

The new release brings better test coverage, fixes some issues found during testing, improves performance, and adds new breaking changes.
* fix: Encode SMT error keys by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/356
* Spec compliance testing, round 1 by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/345
* Iterate through instruction encondings using codegen by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/340
* Refactor of `fuel-crypto` for clarity around safety by @mitchmindtree in https://github.com/FuelLabs/fuel-vm/pull/346 - It removes some public functions from `fuel-crypto` primitives that may cause compilation errors.
* Read contract directly into memory by @freesig in https://github.com/FuelLabs/fuel-vm/pull/342 - Adds new traits `StorageSize`, …

Bump the version to `0.27.0`

---

fuel-asm/src/panic_reason.rs
fuel-vm/src/consts.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/tests/flow.rs

Since we currently implement CALL using recursion, it can overflow the process stack before exceeding the gas limit. Currently that occurs around 95 nested calls, so to be sure I've set the limit to 64 for now. It's hardcoded as a part of the interpreter, as changing that value in a config doesn't currently make much sense.
In the future it would be nice to reduce the stack allocations to a level where the limit of 256 could be reached. Even better would be to not use non-optimized recursion in the first place, and keep the state in a stack instead. I will be attempting a refactor for this in the future. When such refactor is complete, the recursion limit could controlled similarly to the gas limits.
This is a breaking change, although I'd assume that nobody is relying on the behavior …

CALL instruction recursion limit

---

.github/workflows/ci.yml

Attempt to address some of the squashed updates / rebasing headaches by using a merge train instead of requiring all branches to be up-to-date with master before merging.

enable merge queue

---

Cargo.toml

More releases to come, this is mainly to avoid needing to deal with all the breaking changes in one big fuel-core PR.

Release version bump 0.28.0

---

fuel-asm/src/panic_reason.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/tests/blockchain.rs

Make SMO instruction take data ptr as an argument

---

fuel-vm/src/tests/blockchain.rs

There were no tests for these instructions. The tests added here feel a bit redundant, as they essentially just copy the implementation of the instructions themselves. On the hand, at least this makes sure they work

Add tests for cb, bhsh and bhei instructions

---

fuel-tx/src/transaction/id.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/script.rs
fuel-vm/src/checked_transaction.rs

Since checked transactions are guaranteed to have computed all relevant metadata, this PR adds an infallible API to enable fetching the cached transaction ID for Checked\<Tx\> types.
This cleans up a lot of places in https://github.com/FuelLabs/fuel-core/pull/1107 where the consensus parameters would have to be routed even though the transaction id is already known (mainly executor and txpool since they use checked transactions).

Add convenience API for getting transaction ID without ConsensusParameters

---

fuel-types/src/numeric_types.rs

The recent BlockHeight refactoring changed the encoding of some fields, which in turn makes some of the examples not work anymore. For instance, the example in fuel-core readme is now broken. This PR restores the old behavior for `BlockHeight`.

Serialize BlockHeight as integer again

---

Cargo.toml

* Serialize BlockHeight as integer again by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/422
* Duplicate patch from `0.26.3` by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/428
* Adding more unit tests by @freesig in https://github.com/FuelLabs/fuel-vm/pull/390
* Update deps and audit by @freesig in https://github.com/FuelLabs/fuel-vm/pull/429

Bump the version to `0.31.0`

---

Cargo.toml
fuel-vm/src/constraints.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/tests/blockchain.rs

The `SMO` opcode may pass empty array with zero size.

Allow empty range in the checked memory

---

fuel-types/src/numeric_types.rs

Minor nit since we currently only use 4 byte numeric types, but this PR fixes to_bytes to work correctly with alternative sizes.

Fix to_bytes for numeric types

---

Cargo.toml

* Add wide math operations by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/424
* Do not panic when shifting by more than u32::MAX bits by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/433
* Allow empty range in the checked memory by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/436
* Modify "with" functions for consensus parameters by @mitch-fuel in https://github.com/FuelLabs/fuel-vm/pull/446
* Fix to_bytes for numeric types by @Voxelot in https://github.com/FuelLabs/fuel-vm/pull/447
* Addressing minor issues by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/444
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.31.0...v0.32.0

Bump the version to the `0.32.0`

---

CHANGELOG.md
fuel-tx/src/builder.rs
fuel-tx/src/tests/bytes.rs
fuel-tx/src/tests/offset.rs
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/transaction/id.rs
fuel-tx/src/transaction/metadata.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/validity/error.rs
fuel-vm/src/checked_transaction/types.rs
fuel-vm/src/interpreter/executors/main.rs

It fixes several TODO.
The change moves the check of the `contract_id` and `state_root` from VM to the check rules. The change also caches the `contract_root`, `state_root`, and `contract_id` in the metadata.

Moved the check of the `contract_id` and `state_root` from `fuel-vm` to `fuel-tx`

---

CHANGELOG.md
Cargo.toml

[Rendered release notes](https://github.com/FuelLabs/fuel-vm/blob/release/0.33.0/CHANGELOG.md#version-0330)

Bump version to `0.33.0`

---

CHANGELOG.md
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/memory/allocation_tests.rs
fuel-vm/src/tests/memory.rs

This is a critical security bug that allows bypassing memory ownership protection completely.
Exploiting this bug is trivial. Using the following code would make the whole VM memory writable using e.g. SB and SW instructions. This in turn allows for instance performing contract operations using different contracts id.
```
cfs $sp           // Use the bug to set $sp = 0
slli $a, $one, 26 // Set $a to VM_MAX_RAM
aloc $a           // Set $hp = 0, so that the whole memory is in owned heap range
```

Disallow setting $sp < $ssp using CFS and CFSI instructions

---

fuel-vm/src/constraints.rs
fuel-vm/src/error.rs
fuel-vm/src/interpreter/balances.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/contract.rs
fuel-vm/src/interpreter/executors/predicate.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/memory/allocation_tests.rs
fuel-vm/src/interpreter/memory/tests.rs
fuel-vm/src/predicate.rs
fuel-vm/src/tests/blockchain.rs

Removed `CheckedMemRange` and uses `MemoryRange` instead. `MemoryRange` is now always checked, validates and type-converts it's arguments safely.
This is a minimal set of changes required for merging the types. The improvements around memory handling will be used for follow-up PRs which will clean up the memory handling code even more.
Works towards https://github.com/FuelLabs/fuel-vm/issues/474. Partially extracted from https://github.com/FuelLabs/fuel-vm/pull/461.

MemoryRange rework

---

Cargo.toml
fuel-tx/src/transaction/types/input.rs
fuel-vm/src/interpreter/metadata.rs

After https://github.com/FuelLabs/fuel-vm/pull/373 the GTF for data length is not working for `MessageCoinSigned` and `MessageCoinPredicate`

Return the previous behavior of the data length GTF

---

fuel-merkle/src/sparse/merkle_tree.rs

@bvrooman It seems I found a bug=( We use the same storage for leafs and nodes, it means the node can override the leaf that hash `leaf_key == node_hash`

Added a test to show a problem with leaf overriding

---

fuel-vm/src/call.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/gas.rs
fuel-vm/src/interpreter/memory.rs

Originally from https://github.com/FuelLabs/fuel-vm/pull/461 but extracted here for a separate review.
No externally visible changes, only internal readibility improvements.

Minor readibility improvements

---

fuel-asm/Cargo.toml
fuel-crypto/Cargo.toml
fuel-tx/Cargo.toml
fuel-types/Cargo.toml
fuel-vm/Cargo.toml

Fixes a publish failure due to specifying the version of crates which haven't been published yet in dev-deps implicitly via `workspace = true`

dev-deps on local crate must use path

---

CHANGELOG.md
Cargo.toml

Mainly new opcodes prices and small performance improvements in the `BinaryMerkleTree`.
- [#492](https://github.com/FuelLabs/fuel-vm/pull/492) Minor improvements to BMT internals, including a reduction in usage of `Box`, using `expect(...)` over `unwrap()`, and additional comments.
- [#493](https://github.com/FuelLabs/fuel-vm/pull/493) The default `GasCostsValues` is updated according to the benches with `fuel-core 0.19`. It may break some unit tests that compare actual gas usage with expected.
* chore: BMT clean up by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/492
* Update gas prices based on `fuel-core 0.19` by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/493
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.34.0...v0.34.1

Bump version to `0.34.1`

---

fuel-vm/src/tests/crypto.rs

@luizstacio is working on the predicate, and he tried to recover the signer public key from the witness and `TxId`. These tests verify the behavior for the script and predicate on the `fuel-vm` side.

Some additional test to verify ecrecovery with `TxId` and coin witness

---

fuel-asm/src/lib.rs
fuel-asm/src/macros.rs

Work towards https://github.com/FuelLabs/fuel-vm/issues/349. This PR doesn't do externally any visible changes (except renaming some of the arguments), i.e. doesn't add new methods etc. yet. However, this completes hard part of the refactor, and allows more improvements in the future. It refactors the big `macro_rules! impl_instructions` block to smaller pieces so it's easier to modify in the future.

Add argument names to fuel-asm opcodes

---

fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs

The receipt used to show the requested amount of forwarded gas. This PR makes the receipt show the actually forwarded gas amount instead.
See also spec PR to clarify this: https://github.com/FuelLabs/fuel-specs/pull/501

Use correct amount of gas in call receipts when limited by cgas

---

CHANGELOG.md
fuel-vm/src/call.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/code_tests.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/contract.rs
fuel-vm/src/interpreter/contract/tests.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/interpreter/gas.rs
fuel-vm/src/interpreter/gas/tests.rs
fuel-vm/src/tests/metadata.rs

Unified the check that the `ContractId` in inputs by `TouchedContracts` structure.
Check that the contract is in inputs for `CROO` and `CSIZ`. 
Fixed the bug with `total_code_size`.
Fixed the bug with incorrect gas charging per unit.

Bugfixes found during chatting with Auditors on July 7th

---

CHANGELOG.md
fuel-tx/src/receipt.rs
fuel-tx/src/receipt/receipt_std.rs
fuel-tx/src/receipt/sizes.rs
fuel-tx/src/tests/bytes.rs
fuel-types/src/fmt.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/ret_tests.rs
fuel-vm/src/interpreter/log.rs
fuel-vm/src/interpreter/log/tests.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/memory.rs
fuel-vm/src/tests/wideint.rs

- The `data` field is optional now and is not recovered during canonical deserialization. 
- The `len` field is not padded anymore.
ref https://github.com/FuelLabs/fuel-core/issues/1240

Removed the `data` field from canonical serialization and deserialization of receipts

---

CHANGELOG.md
fuel-asm/src/lib.rs
fuel-tx/src/lib.rs
fuel-tx/src/receipt.rs
fuel-tx/src/receipt/receipt_repr.rs
fuel-tx/src/receipt/receipt_std.rs
fuel-tx/src/receipt/sizes.rs
fuel-tx/src/tests/bytes.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/tests/contract.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/496
- Added new `Mint` and `Burn` receipts with serialization and deserialization.
- `mint` and `burn` opcodes accept a new `$rB` register - `sub_id`
- `mint` and `burn` opcodes produce receipts now.

Support of the multi-assets per contract

---

CHANGELOG.md
Cargo.toml

The release mostly fixes funding during the audit and integration with the bridge. But the release also contains some new features like:
- Asynchronous predicate estimation/verification.
- Multi-asset support per contract.
- Support Secp256r1 signature recovery and Ed25519 verificaiton.
- [#486](https://github.com/FuelLabs/fuel-vm/pull/486/): Adds `ed25519` signature verification and `secp256r1` signature recovery to `fuel-crypto`, and corresponding opcodes `ED19` and `ECR1` to `fuel-vm`.
- [#500](https://github.com/FuelLabs/fuel-vm/pull/500): Introduced `ParallelExecutor` trait
and made available async versions of verify and estimate predicates.
Updated tests to test for both parallel and sequential execution.
Fixed a bug in `transaction/check_predicate_owners`.
- …

Release v0.35.0

---

CHANGELOG.md
Cargo.toml

The minor release to trigger publishing of the `fuel-asm` and `fuel-types` to npm.
- [#499](https://github.com/FuelLabs/fuel-vm/pull/499/): The `wasm_bindgen` support of `fuel-asm` and `fuel-types`.
Each new release also publish a typescript analog of the `fuel-asm` and `fuel-types` crates to the npm.
* The `wasm_bindgen` support of `fuel-asm` and `fuel-types` by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/499
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.35.0...v0.35.1

Release v0.35.1

---

.github/workflows/ci.yml

Removing git checks to allow NPM-publish to occur from any branch (fixes [this](https://github.com/FuelLabs/fuel-vm/actions/runs/5650374516/job/15306807035)).

Fixing NPM-publish workflow

---

CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters.rs
fuel-tx/src/transaction/consensus_parameters/gas.rs

This got removed during the last PR:
https://github.com/FuelLabs/fuel-vm/pull/514
Is needed by consumers (`fuel-core`).

Make `ConsensusParameters` Serialize/Derserialize again

---

.npm/.scripts/template/rollup.config.mjs
CHANGELOG.md

Ensures that the WASM binary is initialized [synchronously](https://github.com/rollup/plugins/tree/master/packages/wasm/#synchronous-modules) so that it is available right after being imported.

Initializing WASM synchronously

---

fuel-tx/src/builder.rs

Was removed during: 
https://github.com/FuelLabs/fuel-vm/pull/514

Reimplement `with_params` method for TxBuilder

---

CHANGELOG.md
fuel-asm/src/panic_reason.rs
fuel-vm/src/interpreter/contract.rs
fuel-vm/src/tests/outputs.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/522
This PR also adds a new PanicReason, `TransferZeroCoins`, for this specific issue. `TR` instruction previously used `NotEnoughBalance` for this situation, but it seems highly misleading.
Alternatively we could allow this and modify the spec accordingly.

Make TRO instruction revert on zero coin amount

---

CHANGELOG.md
fuel-asm/src/lib.rs
fuel-crypto/src/lib.rs
fuel-tx/src/lib.rs
fuel-tx/src/transaction/types/utxo_id.rs
fuel-tx/src/tx_pointer.rs
fuel-vm/src/lib.rs

Fixes #521. Adds clippy lints to disallow raw string slicing, so this wont happen again so easily.

Fix a crash in UtxoId::from_str and TxPointer::from_str with multibyte characters

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
ci_checks.sh
fuel-asm/src/encoding_tests.rs
fuel-crypto/src/ed25519.rs
fuel-tx/src/builder.rs
fuel-tx/src/receipt/receipt_repr.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/types.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/input.rs
fuel-tx/src/transaction/types/input/coin.rs
fuel-tx/src/transaction/types/input/contract.rs
fuel-tx/src/transaction/types/input/message.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/output.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/types/utxo_id.rs
fuel-tx/src/transaction/types/witness.rs
fuel-tx/src/transaction/validity.rs
fuel-tx/src/tx_pointer.rs
fuel-vm/src/arith.rs
fuel-vm/src/constraints/reg_key.rs
fuel-vm/src/interpreter/internal.rs

Duplicates changes from https://github.com/FuelLabs/fuel-vm/pull/542 to our `master`

Duplicate changes from 0.35.3 release

---

CHANGELOG.md
README.md
fuel-asm/src/lib.rs
fuel-crypto/README.md
fuel-crypto/src/secp256k1/signature.rs
fuel-crypto/src/secp256r1.rs
fuel-merkle/README.md
fuel-merkle/src/sum/merkle_tree.rs
fuel-tx/README.md
fuel-tx/src/contract.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/input/coin.rs
fuel-tx/src/transaction/types/input/contract.rs
fuel-tx/src/transaction/types/input/message.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/validity.rs
fuel-types/src/array_types.rs
fuel-vm/src/call.rs
fuel-vm/src/checked_transaction.rs
fuel-vm/src/checked_transaction/types.rs

After the reshuffling of the specifications to comply with the new documentation hub format, many of the links in this repo broke. This PR updates all the links to be correct and valid.

Fix urls to specification

---

CHANGELOG.md
Cargo.toml

- [#525](https://github.com/FuelLabs/fuel-vm/pull/525): The `$hp` register is no longer restored to it's previous value when returning from a call, making it possible to return heap-allocated types from `CALL`.
- [#535](https://github.com/FuelLabs/fuel-vm/pull/535): Add better test coverage for TR and TRO.
- [#514](https://github.com/FuelLabs/fuel-vm/pull/514/): Add `ChainId` and `GasCosts` to `ConsensusParameters`. 
Break down `ConsensusParameters` into sub-structs to match usage. Change signatures of functions to ask for
necessary fields only.
- [#532](https://github.com/FuelLabs/fuel-vm/pull/532): The `TRO` instruction now reverts when attempting to send zero coins to an output. Panic reason of this `TransferZeroCoins`, and `TR` was changed to use the same panic reason as well.
- …

Release v0.36.0

---

CHANGELOG.md
fuel-asm/src/macros.rs
fuel-asm/src/panic_instruction.rs

Currently the `reason.instruction` sub-field of `PanicInstruction` is just a raw integer representation of the instruction bytes. This PR changes the `Debug` implementation to decode the instruction when possible. It will also show the bytes in hexadecimal format, which is more useful for debugging as it can be used to spot the instruction in a hexdump, and it shows the opcode byte separately.
This PR also changes the debug format of register (non-immediate) operands to be hexadecimal, as it is the established convention (e.g. the specification lists registers using hex values, and do does most of the test code). 
```rust
reason: PanicInstruction {
reason: OutOfGas,
instruction: 1920991264,
},
```
```rust
reason: PanicInstruction {
reason: ErrorFlag,
instruction: 0,
},
```
```rust
reason: …
```

Instruction debug fmt improvements

---

CHANGELOG.md
Cargo.toml

- [#546](https://github.com/FuelLabs/fuel-vm/pull/546): Improve debug formatting of instruction in panic receipts.
- [#547](https://github.com/FuelLabs/fuel-vm/pull/547): Bump `ed25519-dalek` to `2.0.0` to deal with RustSec Advisory 
- [#524](https://github.com/FuelLabs/fuel-vm/pull/524): Fix a crash in `CCP` instruction when overflowing contract bounds. Fix a bug in `CCP` where overflowing contract bounds in a different way would not actually copy the contract bytes, but just zeroes out the section. Fix a bug in `LDC` where it would revert the transaction when the contract bounds were exceeded, when it's just supposed to fill the rest of the bytes with zeroes.
* Instruction debug fmt improvements by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/546
* Fix a crash in CCP and …

Create Release `0.36.1`

---

.github/workflows/ci.yml
ci_checks.sh
fuel-vm/src/interpreter/balances.rs
fuel-vm/src/interpreter/blockchain/code_tests.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/flow.rs
fuel-vm/src/tests/predicate.rs

Currently, the `fuel-vm` CI is failing because `clap v4.4.1` requires `rustc 1.70.0` or newer. This PR updates the CI's stable Rust version to 1.72.0 and nightly Rust version to 1.74.0 2023-08-28.
See https://github.com/FuelLabs/fuel-vm/actions/runs/6013665712/job/16311620446?pr=574 for example of this failure.

Update CI RUST_VERSION to 1.72.0

---

CHANGELOG.md
fuel-merkle/src/binary/hash.rs

- Closes https://github.com/FuelLabs/fuel-vm/issues/556
This PR enforces all inputs to the internal `node_sum` function to be `Bytes32`.

fix: Fixed length input for BMT `node_sum`

---

fuel-types/src/canonical.rs

Progress towards upgrading `fuel-vm` inside `fuel-core`:
This PR adds `fmt::Display` to `canonical::Error`. This is helpful because it allows `canonical::Error` to be used seamlessly in places where it is replacing `std::io::Error`. Specific areas include:
```
async fn estimate_predicates(
&self,
ctx: &Context<'_>,
tx: HexString,
) -> async_graphql::Result<Transaction> {
let mut tx = FuelTx::from_bytes(&tx.0)?;
...
```
This example requires that the possible error returned by `from_bytes(..)` implements `Display`. Without this implementation, the code will fail to compile.
With this change, the [upgrade branch](https://github.com/FuelLabs/fuel-core/pull/1338) compiles locally without error or warning.

feat: Impl `fmt::Display` for canonical Error

---

fuel-tx/src/transaction/consensus_parameters/gas.rs

Currently some gas costs are not presented in alphabetical order, creating confusion around the way the chainspec gas costs should be ordered. By putting them in alphabetical order, there is a deterministic way to define the gas costs in a chainspec. 
Putting the chainspec gas costs in alphabetical order alone is insufficient, as it creates a discrepancy in the serialized versions of the chainspec. This also causes tests to fail.

fix: Organize `ConsensusParameters` gas costs in alphabetical order

---

CHANGELOG.md
Cargo.toml

* Use dependent cost for missed opcodes by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/537
* Update CI RUST_VERSION to 1.72.0 by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/575
* Remove `debug` feature from `fuel-vm` and use debugger by default. by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/554
* fix: Fixed length input for BMT `node_sum` by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/574
* Use custom derive ser/de instead of std::io by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/533
* feat: Impl `fmt::Display` for canonical Error by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/580
* fix: Organize `ConsensusParameters` gas costs in alphabetical order by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/581
* feat: Configurable …

Upgrade to version 0.37.0

---

CHANGELOG.md
fuel-merkle/Cargo.toml
fuel-merkle/src/binary/merkle_tree.rs
fuel-merkle/src/common/error.rs
fuel-merkle/src/common/node.rs
fuel-merkle/src/common/prefix.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sparse/node.rs
fuel-merkle/src/sum/merkle_tree.rs
fuel-tx/Cargo.toml
fuel-tx/src/transaction/types/utxo_id.rs
fuel-tx/src/transaction/validity/error.rs
fuel-vm/Cargo.toml
fuel-vm/src/error.rs

Follow-up to https://github.com/FuelLabs/fuel-vm/pull/582
Replaces thiserror dependency of no_std crates with a `core::fmt::Display` implementations generated by `derive_more` crate. This is a breaking change, since we lose `std::io::Error` trait impls when `std` feature is enabled.

Replace thiserror with derive_more::Display

---

CHANGELOG.md
Cargo.toml

The release adds `no_std` compatible canonical serialization/deserialization. Along with it, all crates were updated to be `no_std` compatible. The whole repository is now WASM and RiscV compatible.
- [#586](https://github.com/FuelLabs/fuel-vm/pull/586): Added `default_asset` method to the `ContractIdExt` trait implementation, to mirror the `default` method on AssetId in the Sway std lib.
- [#578](https://github.com/FuelLabs/fuel-vm/pull/578): Support `no_std` environments for `fuel-crypto`, falling back to a pure-Rust crypto implementation.
- [#582](https://github.com/FuelLabs/fuel-vm/pull/582): Make `fuel-vm` and `fuel-tx` crates compatible with `no_std` + `alloc`. This includes reworking all error handling that used `std::io::Error`, replacing some `std::collection::{HashMap, HashSet}` …

Release 0.38.0

---

CHANGELOG.md
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-types/src/numeric_types.rs

As suggested in https://github.com/FuelLabs/fuel-core/issues/1334, the `BlockHeight` type should have error-prone arithmetic implementations. In this case it was possible to silently wrap the result, which is even worse.

Remove BlockHeight arithmetic

---

CHANGELOG.md
fuel-asm/Cargo.toml
fuel-asm/src/lib.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/518
Everything seems to be working wihtout it as well.

Remove wee_alloc dependency, use builtin allocator instead

---

CHANGELOG.md
fuel-vm/src/error.rs
fuel-vm/src/predicate.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/181
Also improves error propagation so that predicate error message better reflects the reason for invalidation. For instance, it now includes the disallowed contract opcode which was not accepted in predicate exection context.

Predicate input validation tests

---

CHANGELOG.md
fuel-merkle/Cargo.toml
fuel-merkle/src/binary/node.rs
fuel-merkle/src/binary/root_calculator.rs
fuel-merkle/src/common/position.rs
fuel-tx/Cargo.toml
fuel-vm/Cargo.toml

Adds serialization and deserialization support for the MerkleRootCalculator struct. 
Additional work: 
- getter for MerkleRootCalculator stack
- constructor new_with_stack

Add Serialization and Deserialization support to MerkleRootCalculator

---

CHANGELOG.md
Cargo.toml

- [#603](https://github.com/FuelLabs/fuel-vm/pull/603): Added `MerkleRootCalculator`for efficient in-memory Merkle root calculation.
- [#603](https://github.com/FuelLabs/fuel-vm/pull/606): Added Serialization and Deserialization support to `MerkleRootCalculator`.
- [#595](https://github.com/FuelLabs/fuel-vm/pull/595): Removed `wee_alloc` dependency from `fuel-asm`. It now uses the builtin allocator on web targets as well.
- [#598](https://github.com/FuelLabs/fuel-vm/pull/598): Update cost model for `ldc` opcode to take into account contract size.
- [#604](https://github.com/FuelLabs/fuel-vm/pull/604): Removed `ChainId` from `PredicateId` calculation. It changes the generated address of the predicates and may break tests or logic that uses hard-coded predicate IDs.
- …

Release `0.39.0`

---

CHANGELOG.md
fuel-tx/src/contract.rs
fuel-vm/src/crypto.rs
fuel-vm/src/interpreter/receipts.rs

Related issues: 
- https://github.com/FuelLabs/fuel-vm/issues/610
This PR updates all relevant usages of `binary::in_memory::MerkleTree` inside `fuel-vm` to use `binary::root_calculator::MerkleRootCalculator` for calculating BMT roots.

chore: Use MerkleRootCalculator when only BMT root is needed

---

CHANGELOG.md
fuel-asm/src/panic_reason.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/memory.rs
fuel-vm/src/tests/spec.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/616. Closes https://github.com/FuelLabs/fuel-vm/issues/564.
This PR makes attempting to execute opcodes outside `$is..$ssp` range panic with `MemoryNotExecutable` error. It also separates `ErrorFlag` into `InvalidFlags` and `InvalidInstruction`, which make more sense. Then finally it fixes some tests that incorrectly assumed that any of these were equivalent, and some that had even weirder misconceptions.

Memory write xor execute

---

CHANGELOG.md
Cargo.toml

- [#607](https://github.com/FuelLabs/fuel-vm/pull/607): Added `ECAL` instruction support.
- [#612](https://github.com/FuelLabs/fuel-vm/pull/612): Reduced the memory consumption in all places where we calculate BMT root.
- [#615](https://github.com/FuelLabs/fuel-vm/pull/615): Made `ReceiptsCtx` of the VM modifiable with `test-helpers` feature.
- [#618](https://github.com/FuelLabs/fuel-vm/pull/618): Transaction fees for `Create` now include the cost of metadata calculations, including: contract root calculation, state root calculation, and contract id calculation.
- [#613](https://github.com/FuelLabs/fuel-vm/pull/613): Transaction fees now include the cost of signature verification for each input. For signed inputs, the cost of an EC recovery is charged. For predicate inputs, the cost of a …

Release `v0.40.0`

---

CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/code_tests.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/interpreter/gas.rs
fuel-vm/src/interpreter/gas/tests.rs
fuel-vm/src/tests/blockchain.rs

- https://github.com/FuelLabs/fuel-vm/issues/611

feat: Light and Heavy operation gas costs

---

fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/memory.rs

Replaces unnecessary uses of registers with values of zero and one with their hardwired counterparts. Also replaces zeroing `xor` instructions followed by assignment by just the assignment.

Simplify asm in some tests

---

CHANGELOG.md
Cargo.toml
fuel-tx/src/transaction/types/witness.rs
fuel-tx/src/transaction/validity.rs
fuel-vm/src/interpreter/executors/main.rs

- [#629](https://github.com/FuelLabs/fuel-vm/pull/629): Charge the user for VM initialization.
- [#628](https://github.com/FuelLabs/fuel-vm/pull/628): Renamed `transaction::CheckError` to `transaction::ValidityError`.
Created a new `checked_transaction::CheckError` that combines `ValidityError`
and `PredicateVerificationFailed` errors into one. It allows the return of the
`PredicateVerificationFailed` to the end user instead of losing the reason why predicate verification failed.
- [#625](https://github.com/FuelLabs/fuel-vm/pull/625): Use `ArithmeticError` only for arithmetic operations, and introduce new errors like `BalanceOverflow` for others. Whenever an error is internally caused by a type conversion to `usize`, so that an overflowing value wouldn't map to a valid index anyway, …

Release v0.42.0

---

CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-tx/src/transaction/fee.rs
fuel-vm/src/checked_transaction.rs

This PR updates the `vm_initialization` gas cost to a dependent cost, where it is dependent on the size of the transaction.

chore: Update `vm_initialization` to be dependent cost

---

CHANGELOG.md
Cargo.toml

- [#640](https://github.com/FuelLabs/fuel-vm/pull/640): Update VM initialization cost to dependent cost; this is required because the time it takes to initialize the VM depends on the size of the transaction.
* chore: Update `vm_initialization` to be dependent cost by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/640
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.42.1...v0.42.2

Release v0.42.2

---

.npm/.scripts/prepare-wasm-packages.sh
.npm/README.md
.npm/package.json
.npm/packages/fuel-tx/index.test.cjs
.npm/packages/fuel-tx/index.test.mjs
.npm/pnpm-lock.yaml
CHANGELOG.md
Cargo.toml
fuel-asm/Cargo.toml
fuel-tx/Cargo.toml
fuel-tx/src/lib.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/consensus_parameters.rs
fuel-tx/src/transaction/policies.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/input.rs
fuel-tx/src/transaction/types/input/contract.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/output.rs
fuel-tx/src/transaction/types/output/contract.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/types/storage.rs
fuel-tx/src/transaction/types/utxo_id.rs
fuel-tx/src/transaction/types/witness.rs
fuel-tx/src/transaction/validity.rs
fuel-tx/src/tx_pointer.rs
fuel-types/Cargo.toml
fuel-types/src/array_types.rs
fuel-types/src/numeric_types.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/579
I'm not sure if we need to add serialization and deserialization support to more types, but this should at least provide a good starting point. 
Also, this is still missing some datastructure manipulation, for instance you cannot modify `Policies` easily.

wasm_bindgen support for fuel-tx

---

CHANGELOG.md
fuel-types/src/array_types.rs

For some reason unknown to me, types generated using the `key!` macro were including an extra length byte in front of them when serialized in serde binary formats. This PR removes the leading byte. (The reason was me, although I'm going to blame serde docs here).

Omit extra byte from types like AssetId when serialized with postcard

---

CHANGELOG.md
Cargo.toml

- [#668](https://github.com/FuelLabs/fuel-vm/pull/668): Remove `non_exhaustive` from versionable types for security reasons
* Remove non-exhaustive attribute for versionable types by @MitchTurner in https://github.com/FuelLabs/fuel-vm/pull/668
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.44.0...v0.45.0

Relese 0.45.0

---

.github/workflows/ci.yml

Upgrades the version of Rust used in CI to 1.75 to address a compiler error for `clap` during CI: `package clap v4.5.0 cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0`

Update CI Rust version to 1.75

---

.github/workflows/ci.yml
CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/croo_tests.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/diff.rs
fuel-vm/src/interpreter/diff/storage.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/storage.rs
fuel-vm/src/storage/interpreter.rs
fuel-vm/src/storage/memory.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/util.rs

- https://github.com/FuelLabs/fuel-core/issues/1654
- https://github.com/FuelLabs/fuel-core/issues/1552

feat: Remove ContractsInfo

---

CHANGELOG.md
Cargo.toml

- [#679](https://github.com/FuelLabs/fuel-vm/pull/679): Require less restricted constraint on `MerkleRootStorage` trait. Now it requires `StorageInspect` instead of the `StorageMutate`.
- [#1632](https://github.com/FuelLabs/fuel-core/pull/1632): Removed `ContractsInfo` table. Contract salts and roots are no longer stored in on-chain data.
- [#1632](https://github.com/FuelLabs/fuel-core/pull/1632): Opcode `CROO` now calculates the given contract's root on demand. `CROO` has therefore been changed to a `DependentCost` gas cost.
* Update CI Rust version to 1.75 by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/674
* feat: Remove ContractsInfo by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/673
* Add gasprice to mint tx by @MitchTurner in …

Bump version to `v0.46.0`

---

CHANGELOG.md
Cargo.toml

- [#686](https://github.com/FuelLabs/fuel-vm/pull/686): Implement `serde` for `InterpreterError`.
- [#685](https://github.com/FuelLabs/fuel-vm/pull/685):
The `MaxFee` is a mandatory policy to set. The `MaxFee` policy is used to check that the transaction is valid. 
Added a new stage for the `Checked` transaction - `Ready`. This type can be constructed with the 
`gas_price` before being transacted by the `Interpreter`.
- [#671](https://github.com/FuelLabs/fuel-vm/pull/671): Support dynamically sized values in the ContractsState table by using a vector data type (`Vec<u8>`).
- [#682](https://github.com/FuelLabs/fuel-vm/pull/682): Include `Tip` policy in fee calculation
- [#683](https://github.com/FuelLabs/fuel-vm/pull/683): Simplify `InterpreterStorage` by removing dependency on …

Release `0.47.0`

---

CHANGELOG.md
Cargo.toml

- [#689](https://github.com/FuelLabs/fuel-vm/pull/689): Re-add fields to the checked tx `Metadata` for min and max gas.
- [#689](https://github.com/FuelLabs/fuel-vm/pull/689): Add test helpers and additional getters.
* Fixes during integration with fuel core by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/689
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.47.0...v0.47.1

Release `0.47.1`

---

CHANGELOG.md
fuel-asm/src/args.rs
fuel-vm/src/interpreter/metadata.rs
fuel-vm/src/interpreter/metadata/tests.rs
fuel-vm/src/tests/metadata.rs

Spec PR: https://github.com/FuelLabs/fuel-specs/pull/556

Add GTF getters for tx bytes size and address

---

CHANGELOG.md
Cargo.toml

- [#705](https://github.com/FuelLabs/fuel-vm/pull/705): Added `privileged_address` to the `ConsensusParameters` for permissioned operations(like upgrade of the network).
- [#648](https://github.com/FuelLabs/fuel-vm/pull/648): Added support for generating proofs for Sparse Merkle Trees (SMTs) and proof verification. Proofs can be used to attest to the inclusion or exclusion of data from the set.
- [#709](https://github.com/FuelLabs/fuel-vm/pull/709): Removed `bytecode_length` from the `Create` transaction.
- [#706](https://github.com/FuelLabs/fuel-vm/pull/706): Unified `Create` and `Script` logic via `ChargeableTransaction`. The change is breaking because affects JSON serialization and deserialization. Now `Script` and `Create` transactions have `body` fields that include unique …

Release v0.48.0

---

CHANGELOG.md
Cargo.toml

- [#721](https://github.com/FuelLabs/fuel-vm/pull/721): Added additional logic to the BMT proof verification algorithm to check the length of the provided proof set against the index provided in the proof.
- [#719](https://github.com/FuelLabs/fuel-vm/pull/719): Fix overflow in `LDC` instruction when contract size with padding would overflow.
- [#715](https://github.com/FuelLabs/fuel-vm/pull/715): The `Interpreter` supports the processing of the `Upload` transaction. The change affects `InterpreterStorage`, adding `StorageMutate<UploadedBytes>` constrain.
- [#714](https://github.com/FuelLabs/fuel-vm/pull/714): The change adds a new `Upload` transaction that allows uploading huge byte code on chain subsection by subsection. This transaction is chargeable and is twice as expensive as the …

Release v0.49.0

---

fuel-vm/examples/single_step.rs

Adds a small example to demonstrate single-stepping to show execution trace.

Add a single stepping example

---

fuel-asm/src/macros.rs
fuel-crypto/src/secp256/signature_format.rs
fuel-tx/src/transaction/validity.rs
fuel-vm/fuzz/Cargo.toml
fuel-vm/fuzz/README.md
fuel-vm/fuzz/fuzz_targets/grammar_aware.rs
fuel-vm/fuzz/fuzz_targets/grammar_aware_advanced.rs
fuel-vm/fuzz/src/collect.rs
fuel-vm/fuzz/src/execute.rs
fuel-vm/fuzz/src/lib.rs
fuel-vm/fuzz/src/seed.rs
fuel-vm/src/util.rs

Adds a fuzzer which:
* Can call contracts
* Uses complete scripts with fuzzed script data
* Can use LibAFL
```
cargo install cargo-fuzz
apt install clang pkg-config libssl-dev # for LibAFL
rustup component add llvm-tools-preview --toolchain nightly
```
It is necessary to first convert Sway programs into a suitable format for use as seed input to the fuzzer. This can be done with the following command:
```
cargo run --bin seed <input dir> <output dir>
```
The Rust nightly version is required for executing cargo-fuzz. We also disable AddressSanitizer for a significant speed improvement, as we do not expect memory issues in a Rust program that does not use a significant amount of unsafe code, which our [cargo-geiger](https://github.com/rust-secure-code/cargo-geiger) analysis showed. It makes …

Add advanced fuzzer

---

CHANGELOG.md
fuel-crypto/src/secp256/backend.rs
fuel-types/src/bytes.rs
fuel-types/src/numeric_types.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/code_tests.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/tests/blockchain.rs

LDC opcode was behaving incorrectly in internal contexts, i.e. when called from within a contract.
https://github.com/FuelLabs/fuel-specs/pull/584

Fix ldc opcode in internal contexts

---

CHANGELOG.md
Cargo.toml

- [#725](https://github.com/FuelLabs/fuel-vm/pull/725): Adds more clippy lints to catch possible integer overflow and casting bugs on compile time.
- [#729](https://github.com/FuelLabs/fuel-vm/pull/729): Adds more clippy lints to `fuel-merkle` to catch possible integer overflow and casting bugs on compile time. It also does some internal refactoring.
- [#725](https://github.com/FuelLabs/fuel-vm/pull/725): `UtxoId::from_str` now rejects inputs with multiple `0x` prefixes. Many `::from_str` implementations also reject extra data in the end of the input, instead of silently ignoring it. `UtxoId::from_str` allows a single `:` between the fields. Unused `GasUnit` struct removed.
- [#726](https://github.com/FuelLabs/fuel-vm/pull/726): Removed code related to Binary Merkle Sum Trees (BMSTs). The …

Release v0.50.0

---

fuel-merkle/src/sparse/merkle_tree/node.rs

- Ottersec issue 3 about comment described here: https://fuellabs.slack.com/archives/C06P42TQEFL/p1714101628804279

chore: Remove erroneous comment about placeholder merges

---

CHANGELOG.md
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/tests/flow.rs

Spec PR: https://github.com/FuelLabs/fuel-specs/pull/585
Called contracts shouldn't inherit the `$flag` register.

Zero $flag on call

---

CHANGELOG.md
Cargo.toml

- [#732](https://github.com/FuelLabs/fuel-vm/pull/732):  Adds `reset` method to VM memory.
- [#732](https://github.com/FuelLabs/fuel-vm/pull/732): Makes the VM generic over the memory type, allowing reuse of relatively expensive-to-allocate VM memories through `VmMemoryPool`. Functions and traits which require VM initalization such as `estimate_predicates` now take either the memory or `VmMemoryPool` as an argument. The `Interpterter::eq` method now only compares accessible memory regions. `Memory` was renamed into `MemoryInstance` and `Memory` is a trait now.
- [#743](https://github.com/FuelLabs/fuel-vm/pull/743): Zeroes `$flag` on `CALL`, so that contracts can assume clean `$flag` state.
- [#737](https://github.com/FuelLabs/fuel-vm/pull/737): Panic on instructions with non-zero reserved …

Release v0.51.0

---

CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/memory_client.rs
fuel-vm/src/pool.rs
fuel-vm/src/transactor.rs

Since we zero bytes during the heap allocation, we need to iterate over `n` bytes of memory. It may be a lot of work so we need to charge for it properly.

Use `DependentCost` for `aloc` opcode

---

CHANGELOG.md
Cargo.toml

- [#748](https://github.com/FuelLabs/fuel-vm/pull/748): Make `VmMemoryPool::get_new` async.
- [#747](https://github.com/FuelLabs/fuel-vm/pull/747): Use `DependentCost` for `aloc` opcode. The cost of the `aloc` opcode is now dependent on the size of the allocation.
* Use `DependentCost` for `aloc` opcode by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/747
* Make `VmMemoryPool::get_new` async by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/748
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.51.0...v0.52.0

Release v0.52.0

---

.github/workflows/ci.yml
.github/workflows/scripts/generate_pages_index.py

Closes #745
This PR sets up code coverage reporting. It commits the report to [a branch called `codecov-pages`](https://github.com/FuelLabs/fuel-vm/tree/codecov-pages), which contains a folder for each branch. Branch names are urlsafe-base64-encoded to avoid (security) bugs. Every time a PR workflow runs or the  `master` receives new commits, a CI action pushes updated codecov report there.
The testing for this feature is done in https://github.com/Dentosal/test-repo, and ported here.
Possible improvements:
The configuration has to be done by someone who has permission to edit [the repo settings](https://github.com/FuelLabs/fuel-vm/settings/pages): set deployment from `codecov-pages` branch, like this:

Generate and publish code coverage reports in the CI

---

CHANGELOG.md
fuel-asm/src/lib.rs
fuel-vm/benches/execution.rs
fuel-vm/src/interpreter/alu/muldiv.rs
fuel-vm/src/interpreter/debug.rs
fuel-vm/src/interpreter/ecal.rs
fuel-vm/src/tests/alu.rs
fuel-vm/src/tests/external.rs
fuel-vm/src/tests/memory.rs

Improves test coverage by testing some code paths that were not previously take.  Will not contain any externally visible changes, only adding more tests and cleaning up existing ones.

Add misc tests

---

CHANGELOG.md
Cargo.toml

- [#751](https://github.com/FuelLabs/fuel-vm/pull/751):  Improve test coverage.
- [#753](https://github.com/FuelLabs/fuel-vm/pull/753): Fix an ownership check bug in `CCP` instruction.

Prepare release for v0.53.0

---

CHANGELOG.md
fuel-vm/src/interpreter/executors/instruction.rs

closes https://github.com/FuelLabs/fuel-vm/issues/759
WDOP and WQOP used the incorrect gas units. WDOP will increase from 2 to 3, while WQCP will stay at 3.
This may affect the Rust SDK which sometimes run the VM locally for predicate estimation.
Testnet gas schedule for reference: https://github.com/FuelLabs/chain-configuration/blob/master/ignition/chain_config.json

use the correct gas units for wdop and wqop

---

CHANGELOG.md
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/initialization.rs
fuel-vm/src/tests/validation.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/762

Fixed no zeroing malleable fields for `Create` transaction

---

CHANGELOG.md
fuel-vm/src/interpreter/executors/main.rs

We call the same logic in the `post_execute`

Removed redundant `self.receipts.root()` call

---

CHANGELOG.md
fuel-vm/Cargo.toml
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/tests/mod.rs
fuel-vm/src/tests/predicate.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/756
The `fuel-core` already uses synchronous predicate estimation, so we don't need any other changes.

Take into account spent gas during synchronous predicates estimation

---

CHANGELOG.md
Cargo.toml

- [#770](https://github.com/FuelLabs/fuel-vm/pull/770): Cache contract inputs in the VM.
- [#768](https://github.com/FuelLabs/fuel-vm/pull/768): Charge for LDC opcode before loading the contract into memory.
- [#771](https://github.com/FuelLabs/fuel-vm/pull/771): Take into account spent gas during synchronous predicates estimation.
- [#769](https://github.com/FuelLabs/fuel-vm/pull/769): Use `DependentCost` for `CFE` and `CFEI` opcodes.
- [#767](https://github.com/FuelLabs/fuel-vm/pull/767): Fixed no zeroing malleable fields for `Create` transaction.
- [#765](https://github.com/FuelLabs/fuel-vm/pull/765): Corrected the gas units for WDOP and WQOP.
- [#772](https://github.com/FuelLabs/fuel-vm/pull/772): Removed redundant `self.receipts.root()` call.
* use the correct gas units for wdop and …

Release v0.54.0

---

CHANGELOG.md
fuel-vm/src/checked_transaction/types.rs

Having the base asset id allows to get the base asset balance by just using metadata without consensus parameters.

Store the base asset id in the metadata

---

CHANGELOG.md
fuel-tx/src/builder.rs
fuel-tx/src/lib.rs
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/transaction/types.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/validity/error.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/metadata.rs
fuel-vm/src/tests/validation.rs
fuel-vm/src/util.rs

Specification requires to have one and only one `ContractCreated`=) We forgot to check that we have at least one=D

Require `ContractCreated` output in the `Create` transaction

---

CHANGELOG.md
fuel-vm/src/interpreter/blockchain.rs

The attacker can manipulate input `length` and `contract_len`(by deploying the corresponding contract) and cause memory clear or contract and to be cheap.
We need to charge for the maximum possible value. It will incentivize the caller of the CPP to use the same `length` and `contract_len`.

Fixed the CCP opcode to charge for the length of the input

---

CHANGELOG.md
fuel-merkle/src/common/storage_map.rs
fuel-merkle/src/sparse/in_memory.rs
fuel-merkle/src/storage.rs
fuel-storage/src/impls.rs
fuel-storage/src/lib.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/interpreter/contract.rs
fuel-vm/src/interpreter/diff/storage.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/storage/interpreter.rs
fuel-vm/src/storage/memory.rs
fuel-vm/src/storage/predicate.rs

The change adds new `replace` and `take` methods into the `StorageMutate` traits. These new methods work as the old ones. Old methods were changed to not return the value.
Most of all, places that were using `insert` and `remove` don't need an old value. This helps to remove unnecessary lookups to the storage. An example is the Sparse Merkle tree. It only inserts new nodes and removes old nodes without handling the old values since it is not important for the tree.
I helped to decrease lookups to the storage in the testnet by 30%.

Remove unnecessary look up for old values

---

CHANGELOG.md
fuel-vm/src/interpreter/gas.rs
fuel-vm/src/interpreter/gas/tests.rs

Changed the behavior of the gas charge functions.
Form:
1. Charge
2. Profile
To :
1. Profile
2. Charge
Because the `profile` function expects that it is called before `$cgas` is updated.
Since we don't this code, it is not breaking behavior=)

Fixed charge functions to profile cost before charging

---

CHANGELOG.md
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/memory/tests.rs

Fixes two minor bugs in the memory implementation:
- `grow_stack` was silently truncating the `sp` to `MEM_SIZE` even if it was above that
- Empty ranges at `$hp` would fail ownership check, even if they really should pass
* The `grow_stack` case is not tested, as it's not really reachable externally.

grow_stack and empty $hp range write fixes

---

CHANGELOG.md
fuel-merkle/src/common/node.rs
fuel-merkle/src/common/path_iterator.rs
fuel-merkle/src/common/position.rs
fuel-merkle/src/common/position_path.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sparse/merkle_tree/node.rs

During debugging high storage access in the testnet, I realized that we request left and right children during iteration over the SMT.
While we only need path nodes. When we construct the node back, we can use the same path node to decide who is the right child and who is the left child. In this case we reduce number of storage lookups in two times.

Optimized storage lookups for side nodes in the SMT

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml

- [#781](https://github.com/FuelLabs/fuel-vm/pull/781): Added `base_asset_id` to checked metadata.
- [#784](https://github.com/FuelLabs/fuel-vm/pull/784): Avoid storage lookups for side nodes in the SMT.
- [#787](https://github.com/FuelLabs/fuel-vm/pull/787): Fixed charge functions to profile cost before charging.
- [#783](https://github.com/FuelLabs/fuel-vm/pull/783): Remove unnecessary look up for old values by adding new methods to the `StorageMutate` trait.  The old `insert` and `remove` are now `replace` and `take`. The new `insert` and `remove` don't return a value.
- [#783](https://github.com/FuelLabs/fuel-vm/pull/783): Renamed methods of `StorageWrite` trait from `write`, `replace`, `take` to `write_bytes`, `replace_bytes`, `take_bytes`.
- …

Release v0.55.0

---

CHANGELOG.md
fuel-storage/src/impls.rs

We forgot to add implementation for references.

Implement `MerkleRootStorage` for reference types

---

CHANGELOG.md
Cargo.toml

Version 0.56.0 includes the following changes:
- [#796](https://github.com/FuelLabs/fuel-vm/pull/796): Added implementation of the `MerkleRootStorage` for references.
- [#780](https://github.com/FuelLabs/fuel-vm/pull/780): Added `Blob` transaction, and `BSIZ` and `BLDD` instructions. Also allows `LDC` to load blobs.
- [#795](https://github.com/FuelLabs/fuel-vm/pull/795): Fixed `ed19` instruction to take variable length message instead of a fixed-length one. Changed the gas cost to be `DependentCost`.

Prepare for 0.56.0 release

---

.github/workflows/ci.yml
CHANGELOG.md
ci_checks.sh
fuel-asm/src/macros.rs
fuel-tx/src/tests/offset.rs
fuel-tx/src/transaction/id.rs
fuel-vm/src/util.rs

Updates MSRV to 1.79.0. This is matches fuel-core and is needed by latest wasm tooling. CI currently fails without this update.

Rust 1.79.0

---

fuel-compression/src/impls.rs
fuel-compression/src/traits.rs
fuel-derive/src/compression/compress.rs
fuel-derive/src/compression/decompress.rs
fuel-tx/src/tests/da_compression.rs
fuel-tx/src/transaction/types/chargeable_transaction.rs
fuel-tx/src/transaction/types/input/coin.rs
fuel-tx/src/transaction/types/input/message.rs

Small improvements for test maintenance

Simplifying tests for DA compression

---

CHANGELOG.md
fuel-compression/src/key.rs
fuel-types/src/canonical.rs

Closes #811
* Minor changes to the logic for deserializing arrays, using a [MaybeUninit<T>; N] instead of MaybeUninit<[T]; N>. 
* Dropping initialized values when failing and the array has been partially initialized

Deserialize arrays: avoid leaking partially allocated memory when failing

---

CHANGELOG.md
fuel-tx/src/tests/valid_cases/transaction/upgrade.rs
fuel-tx/src/transaction/types/input.rs
fuel-tx/src/transaction/types/input/repr.rs

Return recipient as an owner for the message inputs

---

CHANGELOG.md
fuel-asm/src/panic_instruction.rs
fuel-asm/src/panic_reason.rs
fuel-tx/src/tests/bytes.rs

Related specification PR: https://github.com/FuelLabs/fuel-specs/pull/609
The main reason for removing it from canonical serialization is to avoid affecting the block ID for different panic reasons. The primary goal is just to know that some operation was done incorrectly; what exactly failed is less important. It reduces the chance of getting different blocks within one panic.

Skip the panic reason from canonical serialization

---

CHANGELOG.md
Cargo.toml

- [#670](https://github.com/FuelLabs/fuel-vm/pull/670): Add DA compression functionality to `Transaction` and any types within
- [#733](https://github.com/FuelLabs/fuel-vm/pull/733): Add LibAFL based fuzzer and update `secp256k1` version to 0.29.1.
- [#825](https://github.com/FuelLabs/fuel-vm/pull/733): Avoid leaking partially allocated memory when array deserialization fails
- [#824](https://github.com/FuelLabs/fuel-vm/pull/824): Use `self` instead of `&self` during decompression.
- [#823](https://github.com/FuelLabs/fuel-vm/pull/823): Returned the old behaviour of the json serialization for policies.
- [#826](https://github.com/FuelLabs/fuel-vm/pull/826): Skip the panic reason from canonical serialization of the panic receipt.
- [#821](https://github.com/FuelLabs/fuel-vm/pull/821): …

Release v0.57.0

---

fuel-tx/src/builder.rs
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/tests/valid_cases/transaction/blob.rs
fuel-tx/src/tests/valid_cases/transaction/upgrade.rs
fuel-tx/src/tests/valid_cases/transaction/upload.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/create.rs
fuel-vm/benches/execution.rs
fuel-vm/examples/external.rs
fuel-vm/examples/single_step.rs
fuel-vm/src/interpreter/debug.rs
fuel-vm/src/interpreter/executors/instruction/tests/reserved_registers.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/interpreter/internal/tests.rs
fuel-vm/src/interpreter/memory/tests.rs
fuel-vm/src/predicate.rs
fuel-vm/src/tests/blockchain.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/external.rs
fuel-vm/src/tests/memory.rs
fuel-vm/src/tests/metadata.rs
fuel-vm/src/util.rs

Previously the `add_random_fee_input()` wasn't actually producing a random input, which was confusing. This PR:
1. adds the `add_fee_input()` which is an equivalent to the former version of `add_random_fee_input()` 
2. modifies the `add_random_fee_input()` to accept an `rng` and provide truly random fee input
For compatibility reasons, all tests that were previously using `add_random_fee_input()` were modified to use `add_fee_input()`.
This change should make the test code more explicit and make it easier to create random transactions in test code.
Follow-up draft PR in `fuel-core`: https://github.com/FuelLabs/fuel-core/pull/2211

Add `fn add_fee_input()` and make `fn add_random_fee_input()` truly random

---

fuel-tx/src/transaction/consensus_parameters.rs

This PR adds the `std::error::Error` implementations for the recently introduced `SettingBlockTransactionSizeLimitNotSupported` custom error type.
It also adds the derived `Display`.
This will make it easier for the consumers to properly use this error type.

Add `Display` and `Error` impls to custom error type `SettingBlockTransactionSizeLimitNotSupported`

---

.github/workflows/ci.yml
.npm/.scripts/prepare-wasm-packages.sh
.npm/package.json
.npm/packages/fuel-asm/index.test.mjs
.npm/packages/fuel-tx/index.test.mjs
.npm/packages/fuel-types/index.test.mjs
.npm/pnpm-lock.yaml
.npm/turbo.json
CHANGELOG.md

The generated WASM/JS code changed in v`0.57.0`, and the regexes used to patch it stopped working.
This prevented dependent NPM packages, including the TS SDK and all apps using it, from building.
```
Error: Can't resolve 'fuel_asm_bg.wasm' in '/.../fuels-ts/node_modules/.pnpm/@fuels+vm-asm@0.57.0/node_modules/@fuels/vm-asm/dist/web'
```
This PR fixes those regexes and updates the essential tools used for packaging.

Fixing WASM-NPM packaging and publishing

---

.github/workflows/ci.yml
.npm/.scripts/prepare-wasm-packages.sh
.npm/package.json
.npm/packages/fuel-asm/index.test.mjs
.npm/packages/fuel-tx/index.test.mjs
.npm/packages/fuel-types/index.test.mjs
.npm/pnpm-lock.yaml
.npm/turbo.json
CHANGELOG.md

* Upgrading turbo and pnpm
* DRY
* Adjusting regex to match any variable name; not only `input`
* Updating changelog
* Fixing pnpm version for workflow
* Adding tests to check if all output files have been patched successfully
* Fixing turbo pipeline
* Adjusting pnpm version
* Trying relative static paths
* Adding temporary log call
(cherry picked from commit dffc2b4cd108c3b8eef11067aaeb081b0c8baa28)

Fixing WASM-NPM packaging and publishing (#835)

---

CHANGELOG.md
Cargo.toml

- [#835](https://github.com/FuelLabs/fuel-vm/pull/835): Fixing WASM-NPM packaging and publishing
* Fixing WASM-NPM packaging and publishing by @arboleya in https://github.com/FuelLabs/fuel-vm/pull/835
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.57.0...v0.57.1

Release v0.57.1

---

CHANGELOG.md
fuel-compression/src/key.rs
fuel-tx/src/transaction/types/input/predicate.rs
fuel-tx/src/transaction/types/script.rs

Implemented `AsRef<[u8]>` and `TryFrom<&[u8]>` for DA compression types: ScriptCode, PredicateCode, RegistryKey. It allows to use `Raw` codec in the `fuel-core`

Implemented `AsRef<[u8]>` and `TryFrom<&[u8]>` for DA compression types

---

CHANGELOG.md
Cargo.toml

Just duplicate the minor release to the `master` branch

Cherry pick Release v0.57.1 (#840)

---

CHANGELOG.md
fuel-crypto/src/secp256/secret.rs

Fixes https://github.com/FuelLabs/fuel-vm/issues/830
Deriving `Default` for the `SecretKey` doesn't exactly make too much sense given that we don't use it anywhere in this codebase, and the fact that `k256::SecretKey` throws an error if the provided byte slice is 0 -
We could have a default impl by using rng, but we should expect consumers of this library to use their own impl, or use `SecretKey::random()`

fix(SecretKey): remove Default implementation

---

CHANGELOG.md
fuel-vm/src/interpreter/alu/wideint.rs
fuel-vm/src/tests/wideint.rs

[Link to related issue(s) here, if any]
Closes https://github.com/FuelLabs/fuel-vm/issues/791
The specification requires that WDCM and WDQCM reset the $of and $err registers, but this was not the case.
Questions:

WDCM and WQCM: reset $of and $err

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/README.md
.clusterfuzzlite/build.sh
.clusterfuzzlite/project.yaml
.github/workflows/cflite_batch.yml
.github/workflows/cflite_cron.yml
.github/workflows/cflite_pr.yml
CHANGELOG.md

Supersedes https://github.com/FuelLabs/fuel-vm/pull/727
This PR introduces fuzzing in our CI using ClusterFuzzLite, roughly following the instructions outlined in the [ClusterFuzzLite Github Actions docs](https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/).

Add ClusterFuzzLite in CI featuring PR fuzzing, batch fuzzing and fuzz coverage reports

---

CHANGELOG.md
fuel-asm/src/lib.rs
fuel-crypto/Cargo.toml
fuel-tx/Cargo.toml
fuel-tx/src/transaction/id.rs
fuel-tx/src/transaction/types/input.rs
fuel-vm/Cargo.toml
fuel-vm/src/checked_transaction.rs
fuel-vm/src/checked_transaction/builder.rs
fuel-vm/src/error.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/executors.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/interpreter/executors/predicate.rs
fuel-vm/src/lib.rs
fuel-vm/src/predicate.rs
fuel-vm/src/storage.rs
fuel-vm/src/storage/memory.rs
fuel-vm/src/storage/predicate.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/predicate.rs
fuel-vm/src/tests/validation.rs
fuel-vm/src/util.rs

Enables predicates to load immutable blobs of code from storage. This helps reduce bloating blockspace with large predicates.
Core changes:
- `$PC` can now jump outside of predicate memory range
- `ldc`, `bldd`, and `bsiz` instructions are allowed inside of predicates (but only for blobs, no contracts)
- verifying or estimating predicates now requires access to blob storage

LDC support in predicates

---

CHANGELOG.md
Cargo.toml

- [#849](https://github.com/FuelLabs/fuel-vm/pull/849): Add a new mode `2` to the LDC that allows to use the memory as a source for code.
- [#848](https://github.com/FuelLabs/fuel-vm/pull/848): Allow usage of the blob opcode `BSIZ`, `BLDD`, and `LDC` with mode `1` in the predicates.
- [#838](https://github.com/FuelLabs/fuel-vm/pull/838): Implemented `AsRef<[u8]>` and `TryFrom<&[u8]>` for DA compression types: ScriptCode, PredicateCode, RegistryKey.
- [#820](https://github.com/FuelLabs/fuel-vm/pull/820): Add fuzzing in CI with ClusterFuzzLite.
- [#848](https://github.com/FuelLabs/fuel-vm/pull/848): All estimation and verification of predicate functionality is reworked and now requires the instance of the storage with predicates.
- [#843](https://github.com/FuelLabs/fuel-vm/pull/843): …

Release v0.58.0

---

CHANGELOG.md
fuel-tx/src/transaction/validity.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/tests/predicate.rs

Fixed incorrect predicate estimation when max predicate gas is less than max tx gas

---

CHANGELOG.md
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/tests/blockchain/ldc_mode_2.rs

The following bug was reported:
> I think we should only copy length_unpadded instead of length [here](https://github.com/FuelLabs/fuel-vm/blob/4310f2e81d679dee046c2438ce43ff03808aad42/fuel-vm/src/interpreter/blockchain.rs#L837), and the remaining length-length_padded should be filled with null bytes.
This PR fixes the issue and adds a test case to show that the padding works correcty. While technically breaking, this is a bugfix release. The patch is released immediately.

Fix incorrect padding of LDC mode 2 and release 0.58.2

---

Cargo.toml

- [#854](https://github.com/FuelLabs/fuel-vm/pull/854): Fixed a bug where LDC mode 2 padding bytes would be copied from memory instead of using zeroes.
* Fix incorrect padding of LDC mode 2 and release 0.58.2 by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/854
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.58.1...v0.58.2

Release v0.58.2

---

.clusterfuzzlite/Dockerfile
CHANGELOG.md

- Closes #856 
This PR fixes the missing coverage reports by removing an unnecessary nightly version pinning. As the OSS-FUZZ base builder image already comes with the latest rust nightly compiler (docs https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/#dockerfile), this version pinning which causes a version conflict in the generated raw profile file.
The fix is to simply remove the pinned compiler version from the dockerfile.
This has been tested and a successful CI run can be observed [here](https://github.com/FuelLabs/fuel-vm/actions/runs/11381732377/job/31663774675), with the generated coverage reports visible [here](https://fuellabs.github.io/fuel-fuzzing-corpus/coverage/latest/report_target/grammar_aware_advanced/linux/src/fuel-vm/report.html).

fix(fuzz_coverage): Don't specify compiler version to avoid raw profile version mismatch

---

CHANGELOG.md
fuel-storage/src/impls.rs
fuel-storage/src/lib.rs
fuel-vm/src/interpreter/blockchain/code_tests.rs
fuel-vm/src/interpreter/blockchain/other_tests.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/interpreter/blockchain/test.rs
fuel-vm/src/interpreter/blockchain/test/scwq.rs
fuel-vm/src/interpreter/blockchain/test/srwq.rs
fuel-vm/src/interpreter/blockchain/test/swwq.rs
fuel-vm/src/interpreter/diff/storage.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/flow/tests.rs
fuel-vm/src/memory_client.rs
fuel-vm/src/storage.rs
fuel-vm/src/storage/interpreter.rs
fuel-vm/src/storage/memory.rs
fuel-vm/src/storage/predicate.rs

[Link to related issue(s) here, if any]

Add the possibility to specify an offset for the read value in StorageRead::read

---

fuel-vm/src/interpreter/crypto.rs

* Use `MemoryOverflow` instead of `ArithmeticOverflow` for memory ptr overflows
* Use `From<PanicReason>` impl of `PanicOrBug` to simplify code
* Simplify some memory access patterns

cleanup for add zk opcodes PR

---

CHANGELOG.md
fuel-asm/src/lib.rs
fuel-asm/src/panic_reason.rs
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-vm/Cargo.toml
fuel-vm/src/interpreter/crypto.rs
fuel-vm/src/interpreter/crypto/tests.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/instruction/tests/reserved_registers.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/predicate.rs

https://github.com/FuelLabs/fuel-specs/issues/615

Add new ZK opcodes

---

CHANGELOG.md
fuel-asm/Cargo.toml
fuel-tx/Cargo.toml
fuel-types/Cargo.toml

Bump `wasm-bindgen` from `0.2.88` to `0.2.97`
N/A

chore: bump wasm-bindgen from `0.2.88` to `0.2.97`

---

CHANGELOG.md
Cargo.toml

- [871](https://github.com/FuelLabs/fuel-vm/pull/871): Add `expiration` policy that prevent a transaction to be inserted after a given block height.
- [870](https://github.com/FuelLabs/fuel-vm/pull/870): Add 3 new ZK-related opcodes: eadd (ecAdd on EVM), emul (ecMul on EVM), epar (ecPairing on EVM)
- [875](https://github.com/FuelLabs/fuel-vm/pull/875): Updated `wasm-bindgen` to `0.2.97`
- [860](https://github.com/FuelLabs/fuel-vm/pull/860): Fixed missing fuzzing coverage report in CI.
- [863](https://github.com/FuelLabs/fuel-vm/pull/863): Changed StorageRead::read to load a serialized value starting from a offset. The function returns an optional value equal to the number of bytes read when defined, or none if the offset specified in input is outside the boundaries of the serialized value …

Release  v0.59.0

---

fuel-tx/Cargo.toml
fuel-tx/src/contract.rs
fuel-tx/src/receipt.rs
fuel-tx/src/transaction/consensus_parameters.rs
fuel-tx/src/transaction/types/blob.rs
fuel-tx/src/transaction/types/chargeable_transaction.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/input/coin.rs
fuel-tx/src/transaction/types/input/message.rs
fuel-tx/src/transaction/types/input/predicate.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/types/upgrade.rs
fuel-tx/src/transaction/types/upload.rs
fuel-tx/src/transaction/types/witness.rs
fuel-tx/src/transaction/validity/error.rs
fuel-vm/Cargo.toml
fuel-vm/src/backtrace.rs
fuel-vm/src/storage/blob_data.rs
fuel-vm/src/storage/contracts_state.rs

Fix https://github.com/FuelLabs/fuel-vm/issues/869
Alternative studied : 
- `derive_more` most maintained but doesn't features we need such as `PartialEq` (https://github.com/JelteF/derive_more/issues/414) might be a good fit in the future.
- `derive-where` same issue and even less maintained.
Educe is nearly a drop-in replacement, one of the maintainer is still pretty active.

Replace derivative by educe

---

CHANGELOG.md
Cargo.toml

- [879](https://github.com/FuelLabs/fuel-vm/pull/879): Debugger state wasn't propagated in contract contexts.
- [878](https://github.com/FuelLabs/fuel-vm/pull/878): Fix the transaction de/serialization that wasn't backward compatible with the addition of the new policy.
(The tests that was failing on `fuel-core` doesn't fail anymore on this branch)

Release 0.59.1

---

CHANGELOG.md
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/debugger.rs
fuel-vm/src/tests/mod.rs

While working on execution traces, I noticed that the receipts are produced in incorrect oder when the debugger is enabled. The PR moves the end-of-execution receipt generation to `run_program`, so it's also done when called using `Interpreter::resume`.
This is technically a breaking change, but it's a bugfix so it doesn't necessarily warrant a breakng-version bump.

bugfix: Produce correct receipts with debugger breakpoints enabled

---

CHANGELOG.md
fuel-merkle/Cargo.toml
fuel-storage/src/impls.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/policies.rs
fuel-types/src/canonical.rs
fuel-vm/src/constraints/reg_key.rs
fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/contract.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/gas.rs
fuel-vm/src/interpreter/receipts.rs
fuel-vm/src/profiler.rs
fuel-vm/src/state.rs

Compilation is currently failing locally due to a warning that lifetimes could be elided having be  promoted to an error. 
See https://github.com/rust-lang/rust/pull/124211/
Compilation is also failing because the derivation of `proptest_derive::Arbitrary` is affected by a reworks of non-local impls 
in rust 1.83.0 (see https://github.com/rust-lang/rust/pull/127117 for the rust side, and https://github.com/proptest-rs/proptest/issues/447 for the proptest issue, https://github.com/proptest-rs/proptest/pull/531/files contains a fix). 
The problem disappears by bumping proptest_derive to the latest version. 

Remove elided lifetimes in associated constant

---

fuel-crypto/Cargo.toml
fuel-crypto/src/secp256/backend/k1/secp256k1.rs
fuel-crypto/src/secp256/signature_format.rs
fuel-vm/Cargo.toml

We spotted that there is some dependencies where we didn't used their STD features in our STD contexts. Leveraging these features allow us to increase our performances in STD contexts.

Better usage of STD features in our dependencies

---

.npm/.scripts/template/src/index.js
CHANGELOG.md

Related to: https://github.com/FuelLabs/fuels-ts/issues/3482
Passing the `module_or_path` directly is deprecated, it now expects an object with the `module_or_path` key ([reference](https://github.com/rustwasm/wasm-bindgen/blob/c35cc9369d5e0dc418986f7811a0dd702fb33ef9/crates/cli/tests/reference/targets-1.d.ts#L25-L34)).
- Using `node@22` on `master`, [build and test](https://github.com/FuelLabs/fuel-vm/blob/a53fc36c58daaa0ca7f6b08b29439799af0d6c6f/.npm/README.md?plain=1#L32-L48) and you'll encounter the following warning:
> using deprecated parameters for the initialization function; pass a single object instead
- Using `node@22` on `ps/fix/deprecation-warning`, build and test, the error should not be present.

fix: deprecation message

---

CHANGELOG.md
fuel-tx/src/tests/valid_cases/input.rs
fuel-tx/src/transaction/validity.rs
fuel-tx/src/transaction/validity/error.rs

Comparing the `nonce` of two messages inputs if enough to decide if they are duplicated or not. Previously we were computing the `message_id` now we avoid this computation and only compare the `nonce`.
It requires us to change the error variant to include `nonce` instead of `message_id`. Because the type of the content has change it's already breaking and so we can change the name also to match this type.
```rust
enum ValidityError {
DuplicateMessageInputId {
message_id: MessageId,
},
...
}
```
```rust
enum ValidityError {
DuplicateInputNonce {
nonce: Nonce,
},
...
}
```

Compare nonce instead of message id of inputs to catch duplicates

---

CHANGELOG.md
fuel-storage/src/impls.rs
fuel-storage/src/lib.rs
fuel-vm/src/interpreter/diff/storage.rs
fuel-vm/src/interpreter/flow.rs
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/storage/interpreter.rs
fuel-vm/src/storage/memory.rs
fuel-vm/src/storage/predicate.rs

When reviewing this fix https://github.com/FuelLabs/fuel-core/pull/2673, it became apparent that the return values from StorageRead and StorageWrite traits are not useful and quite misleading. We require the target buffer to be filled completely, which means the caller already knows the number of bytes written after successful invocation.
The PR removes the return values indicating number of bytes written. It's a breaking change, but the fix on caller side is simple and likely affects fuel-core and execution-tracing only.

Remove unnecessary return values from Storage{Read, Write} methods

---

CHANGELOG.md
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/interpreter/internal/message_tests.rs
fuel-vm/src/tests/debugger.rs

While #889 fixed some receipt generation issues it missed regenerating receipts_root after the debugger is done. Also the in-memory outputs were updated too early.

Bugfix: more receipt generation issues with debugger

---

CHANGELOG.md
fuel-crypto/Cargo.toml
fuel-crypto/src/secp256/signature.rs

This PR adds the `remove_recovery_id()` function to the `Signature`. Recovery ID must be removed from the signature in some use cases and this is done manually in `fuel-core`, for example [here](https://github.com/FuelLabs/fuel-core/blob/master/crates/services/shared-sequencer/src/lib.rs#L258-L260). Therefore, there will be a follow-up PR for the `fuel-core` created.
Closes: https://github.com/FuelLabs/fuel-vm/issues/886

Add the `remove_recovery_id()` to `Signature`

---

CHANGELOG.md
fuel-tx/src/transaction/policies.rs
version-compatibility/Cargo.toml
version-compatibility/src/fuel_tx.rs

We changed the `compress` `decompress` implementation to not be the default one which would lead to use the default serde implementation for each field. Instead we use a custom implementation that will use the custom serde implementations we have for `Policies`

Add fix serailization/deserialization of Policies in compressed transactions to be backward compatible

---

CHANGELOG.md
fuel-asm/src/args.rs
fuel-asm/src/panic_reason.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/repr.rs
fuel-tx/src/transaction/types/upload.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/metadata.rs
fuel-vm/src/tests/metadata.rs
fuel-vm/src/tests/validation.rs

https://github.com/FuelLabs/fuel-vm/issues/812
Add new transactions specific `GTFArgs`, creates new `GTFArgs` to deprecate duplicated one between Script and Create and make them generic for all transactions implementing `ExecutableTransaction`.

Add new tx specific GTFArgs and make new generic GTFArgs to replace duplication

---

CHANGELOG.md
Cargo.toml

- [910](https://github.com/FuelLabs/fuel-vm/pull/910): Fix serialization/deserialization of `Policies` in compressed transactions to be backward compatible.

bump 0.59.2 versions

---

fuel-crypto/Cargo.toml
fuel-crypto/src/lib.rs

See https://github.com/RustCrypto/formats/issues/1684
Fixes CI breakage, for now. More issues like this are to be expected, unless we either pin all versions or update our MSRV to latest edition, which includes rust-version-aware resolver.

Pin base64ct to non-MSRV-breaking version

---

CHANGELOG.md
fuel-vm/src/tests/continue_on_error.rs
fuel-vm/src/tests/mod.rs
fuel-vm/src/util.rs
fuel-vm/src/verification.rs

~~Requires #918~~
Work towards #691
Adds a way to continue vm execution after each error instead of terminating immediately. This can be used to collect multiple execution errors at once, which is useful if you don't know in advance what storage, inputs or outputs the tx is going to need access to.
Names are still subject to bikeshedding.

Dry run mode: continue-on-error handling for "contract not in inputs" 

---

.github/workflows/ci.yml
CHANGELOG.md
fuel-vm/benches/execution.rs
fuel-vm/src/interpreter/diff/tests.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/instruction/tests/reserved_registers.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/predicate.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/interpreter/memory/tests.rs

Force monomorphization of the execute family of functions over predicate vs non-predicate execution. This allows optimizing a branch from the hot VM main loop.
Originally from https://github.com/FuelLabs/fuel-core/pull/2767#issuecomment-2686153439.
Also bumps Rust version in CI to 1.81.0.

Make Interpreter::execute and friends generic over predicate-ness

---

CHANGELOG.md
Cargo.toml

- [901](https://github.com/FuelLabs/fuel-vm/pull/901): Add `Display` implementation to `Receipt` enum.
- [896](https://github.com/FuelLabs/fuel-vm/pull/896): Expose `leaf_sum` and allow binary `MerkleTree` to be built from existing precomputed leafs.
- [882](https://github.com/FuelLabs/fuel-vm/pull/882): Add a lot of new `GTFArgs` including generic ones that will replace old tx type specific.
- [909](https://github.com/FuelLabs/fuel-vm/pull/909): Add the `remove_recovery_id()` to `Signature`.
- [915](https://github.com/FuelLabs/fuel-vm/pull/915): Added support for `AttemptContinue` verifier, that collects and ignores some errors instead of terminating execution. This is meant to help with gathering tx dependencies.
- [900](https://github.com/FuelLabs/fuel-vm/pull/900): Change the error …

Release v0.60.0

---

.github/workflows/ci.yml
.github/workflows/create_version.yml

This PR fixes various issues spotted when doing the first release on fuel-core: https://github.com/FuelLabs/fuel-core/pull/2877.
Here is a list : 
- Added a little debug print
- Escape backquote
- Keep new line in description of changes
- Add indentation in newline in description of changes

Add various fixes creation version github Action

---

.changes/breaking/934.md
fuel-vm/src/checked_transaction.rs
fuel-vm/src/error.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/predicate.rs
fuel-vm/src/predicate.rs
fuel-vm/src/tests/predicate.rs

@luizstacio posted on slack:
> It would be good to have the input index of the predicate that failed on this error: Invalid transaction data: `PredicateVerificationFailed(Panic(PredicateReturnedNonOne))`  Right now, with many predicates on a single TX, it is difficult for me to say which one is returning false.
The PR adds `input_index` field to `PredicateVerificationFailed` variants that need use it.
This breaks serde deserialization of old `PredicateVerificationFailed` into the new type, but I don't think we depend on that anywhere. Maybe @xgreenx knows about this one?

Include input_index of the predicate that failed verification

---

.changes/breaking/938.md
fuel-merkle/src/sparse/in_memory.rs
fuel-merkle/src/sparse/merkle_tree.rs
fuel-merkle/src/sparse/proof.rs
fuel-merkle/tests-data/fixtures/Test Update With Empty Data Changes Root.yaml
fuel-merkle/tests-data/fixtures/Test Update With Empty Data.yaml

closes #937 
This PR removes the problematic check for empty values in the SMT `update` function (and the equivalent filtering in `from_set`). This makes SMTs able to commit to empty values, which we need for the proof system for the `ProcessedTransactions` table.
Additionally, to better reflect the behavior I renamed the `update` method to `insert`.

feat: Allow empty values in sparse merkle trees

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
fuel-crypto/Cargo.toml
fuel-crypto/src/lib.rs
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/memory/allocation_tests.rs

[Link to related issue(s) here, if any]
- none
- we zero out the dirty memory when reallocating the heap. this is only detectable after a reset.
- we need to do this

fix(memory_instance): zero out heap memory when reallocating after reset

---

.github/workflows/ci.yml
CHANGELOG.md
fuel-vm/src/interpreter/memory.rs
fuel-vm/src/interpreter/memory/allocation_tests.rs

backport similar to https://github.com/FuelLabs/fuel-vm/pull/941

fix(memory_instance): zero out heap memory when reallocating after reset (backport 0.60.1)

---

CHANGELOG.md
Cargo.toml

Bump version of `fuel-vm` to `0.60.2`

Bump version to `0.60.2`

---

.changes/added/899.md
.changes/added/939.md
.changes/breaking/778.md
.changes/breaking/933.md
.changes/breaking/934.md
.changes/breaking/935.md
.changes/breaking/936.md
.changes/breaking/938.md
.changes/changed/913.md
.changes/fixed/940.md
CHANGELOG.md
Cargo.toml

- [778](https://github.com/FuelLabs/fuel-vm/pull/778): Add `SubAssetId` newtype that's used instead of `Bytes32`.
- [933](https://github.com/FuelLabs/fuel-vm/pull/933): Don't perform balance update if the change is zero
- [934](https://github.com/FuelLabs/fuel-vm/pull/934): Add `input_index` of the failed predicate to `CheckError::PredicateVerificationFailed`.
- [935](https://github.com/FuelLabs/fuel-vm/pull/935): Bump Rust version to `1.85.0`.
- [936](https://github.com/FuelLabs/fuel-vm/pull/936): Update Rust edition to 2024.
- [938](https://github.com/FuelLabs/fuel-vm/pull/938): Rename `update` method to `insert` on sparse merkle tree, and allow inserting empty values.
- [899](https://github.com/FuelLabs/fuel-vm/pull/899): Add a feature that propose `u32` `tx_pointer` instead of `u16` …

Release v0.61.0

---

.github/workflows/ci.yml

Problem discovered during last release, where this job causes CI to fail:
https://github.com/FuelLabs/fuel-vm/actions/runs/14853766345

hotfix: Check changelog job should only run on PRs

---

.changes/added/953.md
fuel-tx/src/lib.rs

Should have been included in https://github.com/FuelLabs/fuel-vm/pull/778 but we missed it then. Discovered while updating fuel-core to use the new 0.61.0 release.

feat: Expose SubAssetId in fuel-tx

---

.changes/added/953.md
CHANGELOG.md
Cargo.toml

- [953](https://github.com/FuelLabs/fuel-vm/pull/953): feat: Expose SubAssetId in fuel-tx

Release v0.61.1

---

.changes/breaking/959.md
fuel-storage/src/lib.rs
fuel-tx/src/contract.rs
fuel-vm/src/storage/blob_data.rs
fuel-vm/src/storage/contracts_state.rs

closes #958 
This PR adds a `Borrow` trait bound to the owned types in the `Mappable` trait. This should improve ergonomics in generic code where we want to use the non-owned value types from the owned ones.
Since this is a limitation in the public interface of a pretty fundamental type, we should be cautious to merge it. However, since we already have an inverse `ToOwned` bound (albeit indirectly with an intermediate `From` conversion), it should be safe to assume that all existing instances are of types where they either already implement the required `Borrow` or should implement it but haven't already.
I have verified that the latest `fuel-core` compiles with this additional bound.

feat: Add `Borrow` trait bounds to owned types in `Mappable` trait

---

.changes/added/922.md
.changes/added/923.md
.changes/added/925.md
.changes/added/953.md
.changes/breaking/959.md
CHANGELOG.md
Cargo.toml

- [959](https://github.com/FuelLabs/fuel-vm/pull/959): Add Borrow trait bounds to owned types in Mappable trait.
- [922](https://github.com/FuelLabs/fuel-vm/pull/922): Add NIOP instruction to perform overflow-checked calculations on u8, u16, and u32 integers
- [923](https://github.com/FuelLabs/fuel-vm/pull/923): Load and store instructions for u16 and u32
- [925](https://github.com/FuelLabs/fuel-vm/pull/925): Add jump-and-link instruction `JAL` that can be used to implement efficient subroutine calls.
- [953](https://github.com/FuelLabs/fuel-vm/pull/953): feat: Expose SubAssetId in fuel-tx

Prepare for 0.62.0 release

---

.changes/breaking/963.md
Cargo.toml
fuel-asm/Cargo.toml
fuel-asm/src/lib.rs
fuel-crypto/Cargo.toml
fuel-merkle/Cargo.toml
fuel-tx/Cargo.toml
fuel-types/Cargo.toml
fuel-vm/Cargo.toml
fuel-vm/src/checked_transaction.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/ecal.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/interpreter/internal.rs
fuel-vm/src/predicate.rs
fuel-vm/src/tests/external.rs
fuel-vm/src/tests/predicate.rs
version-compatibility/Cargo.toml

See https://github.com/FuelLabs/fuel-vm/pull/945#issuecomment-2829271997
Adds `ECAL` state parameter to some predicate-related APIs. Allows `ECAL` instruction during predicate execution. Exposes `Interpreter::context` that can be used by the `ECAL` handler to determine if it's inside a predicate.

Allow setting ECAL for predicate exection

---

.changes/breaking/963.md
CHANGELOG.md
Cargo.toml

- [963](https://github.com/FuelLabs/fuel-vm/pull/963): Adds `ECAL` state parameter to some predicate-related APIs. Allows `ECAL` instruction during predicate execution. Exposes `Interpreter::context` function that can be used by the `ECAL` handler to determine if it's inside a predicate.

Prepare for 0.63.0 release

---

fuel-merkle/src/common/storage_map.rs
fuel-merkle/src/jellyfish.rs
fuel-merkle/src/jellyfish/in_memory.rs

This feature implements a Jmt backed by two in-memory hashmaps (for the tree nodes and value preimages), and an optional value (to keep track of the latest version of the tree). The implementation makes use of the generic implementation of a Jmt over storage traits. 
The following tests are provided: 

[feature/jmt (4/4]: In memory implementation of Jmt backed by storage traits + tests

---

fuel-merkle/src/common/storage_map.rs
fuel-merkle/src/jellyfish.rs
fuel-merkle/src/jellyfish/in_memory.rs
fuel-merkle/src/jellyfish/merkle_tree.rs
fuel-merkle/src/jellyfish/proof.rs

This PR implements the functionalities to generate and verify both proof of inclusion and exclusion for a Jmt.
Tests are provided in the last PR of this feature.

[feature/jmt (3/4)] Proof generation and verification

---

.changes/added/971.md
.changes/added/972.md
.changes/breaking/971.md
.changes/breaking/972.md
.changes/fixed/971.md
CHANGELOG.md
Cargo.toml

- [971](https://github.com/FuelLabs/fuel-vm/pull/971): All `Vec<u8>` fields in the transaction now use `Bytes` type. This type has truncated `Debug` string, and has optimized serialization and deserialization for `postcard` and `binacode` encodings. The new encoding is compatible(was tested) for `serde_json`, `bincode`, `postcard`.
`StateTransition` and `StateTransitionRef` now contains `Verifier` generic from the VM.
- [972](https://github.com/FuelLabs/fuel-vm/pull/972): A new policy has been added to track the owner of the transaction. Serialization and deserialization should now support a new variant to decode a new policy.
- [971](https://github.com/FuelLabs/fuel-vm/pull/971): Added a new `into_transact` method for the `Interpreter` to return `StateTransition` with `receipts`. It …

Release v0.64.0
