FuelLabs/fuel-vm

src/interpreter/flow.rs
tests/contract.rs

There were several blocking todo's preventing contract calls from working properly, this PR should address all of them.

Address missing functionality in call opcode

---

Cargo.toml

for releasing the contract call opcode fixes

0.5.1 version bump

---

Cargo.toml
src/interpreter/executors/instruction.rs
src/interpreter/flow.rs
src/interpreter/gas.rs
src/interpreter/gas/consts.rs
tests/flow.rs

Bump fuel-asm to add JNZI. Implement JNZI in VM.

---

.github/workflows/ci.yml

cargo test with serde added to CI

---

Cargo.toml

bump to v0.11.1

---

src/interpreter/alu.rs
src/interpreter/executors/instruction.rs
tests/alu.rs

Fixes https://github.com/FuelLabs/fuel-vm/issues/142

Set $rA to zero on EXP/EXPI overflow

---

Cargo.toml

releases non-breaking fixes for tx maturity:
- https://github.com/FuelLabs/fuel-vm/pull/154
- https://github.com/FuelLabs/fuel-vm/pull/160

patch release 0.12.1 for tx maturity fixes

---

src/error.rs
src/interpreter/flow.rs
src/interpreter/gas.rs
tests/cgas_overflow.rs

I'm not sure if this is actually the correct approach, so please review carefully.
Also fortifies some gas arithmetics using `checked_*` methods, as per our discussion with @Voxelot.

Fix CGAS overflow bug

---

src/interpreter/executors/instruction.rs
src/interpreter/metadata.rs
src/lib.rs
tests/metadata.rs

Implements the `GTF` instruction.
The tests are being developed in parallel. This PR is released so the accumulated breaking changes can be unblocked for `fuel-core`.
The tests are expected to be added only incrementally, so they can be released as patch (with eventual bugfixes, if applicable)

Implement `GTF` instruction

---

Cargo.toml

* Add tests for `GTF` instruction by @vlopes11 in https://github.com/FuelLabs/fuel-vm/pull/178
* Update fuel-tx to v0.17 by @vlopes11 in https://github.com/FuelLabs/fuel-vm/pull/180
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.13.0...v0.14.0

Bump to v0.14.0

---

src/interpreter/blockchain.rs
src/interpreter/contract.rs
src/interpreter/memory.rs

All instructions that writes data to a register must be shielded by the
assertion that the register is writable

Assert non-writable property of reserved registers

---

src/call.rs
src/error.rs
src/interpreter/blockchain.rs

Addresses `blockchain.rs` for issue #170

Implement safe arithmetic for blockchain mod

---

src/interpreter/contract.rs
src/interpreter/flow.rs
src/memory_client.rs

Closes issue #213 
Signed-off-by: Mitch Martin <mitch.martin@fuel.sh>
Remove occurrences tripping [needless_borrowed_reference](https://rust-lang.github.io/rust-clippy/master/#needless_borrowed_reference)

Remove needless_borrowed_reference

---

Cargo.toml

* Remove needless_borrowed_reference by @mitch-fuel in https://github.com/FuelLabs/fuel-vm/pull/212
* Add `Interpreter::prepare_call` by @vlopes11 in https://github.com/FuelLabs/fuel-vm/pull/215
* @mitch-fuel made their first contribution in https://github.com/FuelLabs/fuel-vm/pull/212
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.18.0...ddd

Bump to v0.18.1

---

src/consts.rs
src/error.rs
src/interpreter/contract.rs

Part of #170.
Adds checked arithmetic functions to `contract.rs`

Safe Arithmetic Implementation for contract.rs

---

src/interpreter/gas.rs

A warning comment to help with #197

Add warning comment to gas_cost_const

---

Cargo.toml

Signed-off-by: Mitch Martin <mitch.martin@fuel.sh>

bump version to 0.21

---

src/call.rs
src/interpreter/blockchain.rs
src/interpreter/executors/instruction.rs
tests/backtrace.rs
tests/blockchain.rs
tests/code_coverage.rs
tests/flow.rs

Closes #52. No functional changes, only code simplification.

Define WORD_SIZE only once

---

tests/alu.rs

Add ALU test cases for MLOG instruction

---

Cargo.toml

* Skip empty `Script` transaction by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/284
* Update LICENSE by @SilentCicero in https://github.com/FuelLabs/fuel-vm/pull/281
* @SilentCicero made their first contribution in https://github.com/FuelLabs/fuel-vm/pull/281
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.22.5...v0.22.6

Bump version to `0.22.6`

---

.github/workflows/ci.yml
Cargo.toml
fuel-crypto/src/mnemonic.rs
fuel-tx/src/builder.rs
fuel-vm/Cargo.toml

- Fix compile errors for default crate features.
- Add checks to ci.

Fix features

---

fuel-vm/src/interpreter/blockchain.rs
fuel-vm/src/interpreter/executors/predicate.rs
fuel-vm/src/interpreter/memory.rs

make try_mem_write and try_zeroize testable to show bug in current impl
Now also include the fix

Show and fix bug in try_mem_write

---

README.md

I realized this repo is missing one, and the repo page looks rather weird without it.

Add a top-level readme file

---

fuel-vm/Cargo.toml
fuel-vm/src/gas.rs

Required by https://github.com/FuelLabs/fuel-core/pull/917

Make GasCosts serdeable

---

Cargo.toml

includes fixes for GTF mapping codes

bump 0.25.2

---

fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/flow.rs

After this, we should be able to freely increase or remove `VM_MAX_NESTED_CALLS`

Make call instruction implementation non-recursive

---

fuel-tx/src/receipt.rs
fuel-tx/src/receipt/receipt_std.rs
fuel-tx/src/receipt/sizes.rs
fuel-tx/src/tests/bytes.rs
fuel-tx/src/transaction/types/output.rs

https://github.com/FuelLabs/fuel-specs/pull/467

Remove `message_id` field from the receipt

---

fuel-asm/src/panic_reason.rs
fuel-vm/src/interpreter/executors/instruction.rs
fuel-vm/src/tests/flow.rs

Remove nested call limit

---

Cargo.toml

bump to 0.28.1

---

.github/workflows/ci.yml

- upgrade to buildjet runners
- enable build caching

Upgrade runners

---

Cargo.toml

release changes for block_height scalar and recent updates to SMO

0.29.0 release prep

---

Cargo.toml

Should not be released until #419 is merged

bump to 0.30.0 in support of chain id

---

fuel-vm/Cargo.toml
fuel-vm/src/interpreter/executors/instruction.rs

Duplicates the https://github.com/FuelLabs/fuel-vm/pull/427

Duplicate patch from `0.26.3`

---

.github/workflows/ci.yml
.github/workflows/nightly-cargo-audit.yml
fuel-crypto/Cargo.toml
fuel-crypto/src/mnemonic.rs
fuel-vm/Cargo.toml

Just bump some out of date deps and bump the audit routine. Also adds the audit check to each pr

Update deps and audit

---

Cargo.toml
fuel-vm/src/constraints.rs
fuel-vm/src/interpreter/blockchain/smo_tests.rs
fuel-vm/src/tests/blockchain.rs

Duplicate https://github.com/FuelLabs/fuel-vm/pull/435 for the `master`

Allow empty range in the checked memory

---

CHANGELOG.md

It adds an empty changelog file we need to update during each PR. The main goal of it is to highlight all critical changes that affect end users. Also, it will improve our documentation and will make releases simpler.
Also, for some very critical changes, we will provide a guide with an upgrade strategy. It will describe the context of the change for PR reviewers and will be helpful in the future for users.

Add empty changelog file

---

fuel-tx/src/builder.rs
fuel-tx/src/contract.rs
fuel-tx/src/transaction.rs
fuel-vm/src/checked_transaction.rs

Minor improvements during integration with `fuel-core`

---

fuel-merkle/benches/smt.rs
fuel-merkle/src/sparse/hash.rs
fuel-merkle/src/sparse/node.rs

With some additional optimizations it works even better=)

Optimize common operations

---

CHANGELOG.md
Cargo.toml
fuel-crypto/Cargo.toml
fuel-crypto/src/ed25519.rs
fuel-vm/Cargo.toml
fuel-vm/src/interpreter/crypto/tests.rs
fuel-vm/src/tests/crypto.rs

Bump dalek version to deal with security vulnerability

---

CHANGELOG.md
fuel-tx/src/tests/valid_cases/input.rs
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/input.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/validity.rs
fuel-vm/src/checked_transaction.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/interpreter/executors/main/tests.rs
fuel-vm/src/predicate.rs
fuel-vm/src/tests/crypto.rs
fuel-vm/src/tests/metadata.rs
fuel-vm/src/tests/predicate.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/597

Remove `ChainId` from `PredicateId` calculation

---

CHANGELOG.md
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/transaction/consensus_parameters.rs
fuel-tx/src/transaction/types/create.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/src/transaction/types/script.rs
fuel-tx/src/transaction/validity.rs
fuel-tx/src/transaction/validity/error.rs
fuel-tx/src/transaction/validity/tests.rs

- https://github.com/FuelLabs/fuel-vm/issues/384

feat: Enforce maximum tx size

---

CHANGELOG.md
Cargo.toml

* Upgrade to Rust 1.73 and fix related todo by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/626
* feat: Light and Heavy operation gas costs by @bvrooman in https://github.com/FuelLabs/fuel-vm/pull/622
* Simplify asm in some tests by @Dentosal in https://github.com/FuelLabs/fuel-vm/pull/631
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.40.0...v0.41.0

Release `v0.41.0`

---

CHANGELOG.md
Cargo.toml

- [#643](https://github.com/FuelLabs/fuel-vm/pull/643): Fixed json deserialization of array fuel types from the file.
* Fixed json deserialization of array fuel types from the file by @sdankel in https://github.com/FuelLabs/fuel-vm/pull/643
* @sdankel made their first contribution in https://github.com/FuelLabs/fuel-vm/pull/643
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.43.0...v0.43.1

Release v0.43.1

---

CHANGELOG.md
fuel-vm/examples/external.rs
fuel-vm/src/interpreter.rs
fuel-vm/src/interpreter/constructors.rs
fuel-vm/src/interpreter/diff/storage.rs
fuel-vm/src/interpreter/ecal.rs
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/memory_client.rs
fuel-vm/src/transactor.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/652

Add state to ECAL handler

---

CHANGELOG.md
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/input.rs
fuel-tx/src/transaction/types/output.rs
fuel-tx/test-helpers/src/lib.rs
fuel-vm/src/checked_transaction.rs
fuel-vm/src/checked_transaction/balances.rs

Part of https://github.com/FuelLabs/fuel-core/issues/1544

Make public types versionable

---

CHANGELOG.md
fuel-vm/src/interpreter/debug.rs
fuel-vm/src/state/debugger.rs

Add batch changes to breakpoints

---

CHANGELOG.md
fuel-tx/src/builder.rs
fuel-tx/src/tests/bytes.rs
fuel-tx/src/tests/valid_cases/transaction.rs
fuel-tx/src/transaction.rs
fuel-tx/src/transaction/types/mint.rs
fuel-tx/test-helpers/src/lib.rs

Closes: https://github.com/FuelLabs/fuel-vm/issues/663

Add gasprice to mint tx

---

CHANGELOG.md
fuel-storage/src/lib.rs
fuel-vm/src/storage/interpreter.rs

Related https://github.com/FuelLabs/fuel-core/issues/1589

Require less restricted constraint on `MerkleRootStorage` trait

---

CHANGELOG.md
fuel-vm/src/interpreter/blockchain.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/758

Charge for LDC opcode before loading the contract into memory

---

CHANGELOG.md
fuel-tx/src/transaction/consensus_parameters/gas.rs
fuel-tx/src/transaction/consensus_parameters/gas/default_gas_costs.rs
fuel-vm/src/interpreter/executors/instruction.rs

Closes https://github.com/FuelLabs/fuel-vm/issues/760

Use `DependentCost` for `CFE` and `CFEI` opcodes

---

CHANGELOG.md
Cargo.toml
fuel-merkle/src/tests/binary_verify.rs

- [#776](https://github.com/FuelLabs/fuel-vm/pull/776): Charge for max length in LDC opcode.
- 
* Charge for max length in LDC opcode by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/776
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.54.0...v0.54.1

Release v0.54.1

---

.github/workflows/ci.yml

Use companies fork of the `publish-crates` action

---

.github/CODEOWNERS

Mimics https://github.com/FuelLabs/fuel-core/pull/2179

chore: Add initial CODEOWNERS file

---

CHANGELOG.md

This PR adds changes to the changelog that should have been added in [#829](https://github.com/FuelLabs/fuel-vm/pull/829)

Update changelog to cover breaking changes around `add_random_fee_input()`

---

CHANGELOG.md
Cargo.toml

- [#852](https://github.com/FuelLabs/fuel-vm/pull/852): Fixed incorrect predicate estimation when max predicate gas is less than max tx gas.
* Fixed incorrect predicate estimation when max predicate gas is less than max tx gas by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/852
**Full Changelog**: https://github.com/FuelLabs/fuel-vm/compare/v0.58.0...v0.58.1

Release v0.58.1

---

.github/workflows/ci.yml

This change will provide the token required to deploy to NPM.
> [!NOTE]
> This step required manual approval before the workflow ran.

chore: allow releases to NPM

---

CHANGELOG.md
fuel-vm/src/interpreter/executors/main.rs
fuel-vm/src/tests/predicate.rs

Ignore the owner of the predicate during the estimation of the predicate

---

.changes/breaking/935.md
.clusterfuzzlite/Dockerfile
.github/workflows/ci.yml
Cargo.toml
fuel-asm/Cargo.toml
fuel-compression/Cargo.toml
fuel-crypto/Cargo.toml
fuel-derive/Cargo.toml
fuel-merkle/Cargo.toml
fuel-storage/Cargo.toml
fuel-tx/Cargo.toml
fuel-types/Cargo.toml
fuel-vm/Cargo.toml

Related to https://github.com/FuelLabs/fuel-core/pull/2887

Update Rust version to 1.85

---

CHANGELOG.md

The previous one didn't match what's expected by the GitHub Actions preventing the automatic changelog creation to work.

Fix title of the unreleased section in changelog. 

---

fuel-vm/src/checked_transaction.rs
fuel-vm/src/interpreter/executors/main.rs

See https://github.com/FuelLabs/fuel-vm/pull/963#discussion_r2283286433 and https://github.com/FuelLabs/fuel-vm/pull/963#discussion_r2283282436

Ecal in predicates follow-up
